package View;

import Connect.Connect;
import Control.ConvertCurrency;
import Control.CtrlPhieuThu;
import Edit.Edit;
import Model.ModPhieuThu;
import Object.ObjKhachHang;
import Object.ObjPhieuThu;
import java.awt.Color;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;

import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Thanh
 */
public class FormQuanLiPhieuThu extends javax.swing.JFrame {

    Edit editFrm = new Edit();
    ArrayList<ObjPhieuThu> listPT = new ArrayList<>();
    ArrayList<ObjKhachHang> listCbbKH = new ArrayList<>();
    ArrayList<ObjKhachHang> listCbbTimTheoKH = new ArrayList<>();
    CtrlPhieuThu CtrlPT = new CtrlPhieuThu();
    ObjKhachHang objKH = new ObjKhachHang();
    ObjPhieuThu objPT = new ObjPhieuThu();
    ModPhieuThu modPT = new ModPhieuThu();
    SimpleDateFormat dt = new SimpleDateFormat("dd/MM/yyyy  hh:mm:ss a");
    SimpleDateFormat dt1 = new SimpleDateFormat("dd/MM/yyyy");
    ConvertCurrency conCurrency =new ConvertCurrency();
    private int flag = 0;
    

    /**
     * Creates new form frmQuanLiPhieuThu
     */
    public FormQuanLiPhieuThu() {
        initComponents();
        setLocationRelativeTo(null);

        jPanel9.setBackground(new Color(0, 0, 0, 0));

        JPanel ListPanel[] = new JPanel[]{jPanel3, jPanel4, jPanel5, jPanel10};
        editFrm.MakeTransparentPanel(ListPanel);

        JPanel ListTitle[] = new JPanel[]{jPnDSPT, jPnThongtinKH, jPnThongtinPT, jPnTracuuPT};
        editFrm.MakeTransparentTitle(ListTitle);

        JPanel ListButton[] = new JPanel[]{jBtnBack, jBtnHuy, jBtnLamMoi, jBtnLuu, jBtnSua, jBtnThem, jBtnTimKiem, jBtnXemPhieuIn, jBtnXoa};
        editFrm.MakeTransparentButton(ListButton);

        editFrm.MakeTransparentTable(jScrDSPT, jTbDSPT);

        jtxtMaPT.setText(CtrlPT.TaoMaPT());
       
        LoadForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnBack = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jBtnXemPhieuIn = new javax.swing.JPanel();
        jlblIn = new javax.swing.JLabel();
        jBtnThem = new javax.swing.JPanel();
        jlblThem = new javax.swing.JLabel();
        jBtnXoa = new javax.swing.JPanel();
        jlblXoa = new javax.swing.JLabel();
        jBtnSua = new javax.swing.JPanel();
        jlblSua = new javax.swing.JLabel();
        jBtnLuu = new javax.swing.JPanel();
        jlblLuu = new javax.swing.JLabel();
        jBtnHuy = new javax.swing.JPanel();
        jlblHuy = new javax.swing.JLabel();
        jBtnTimKiem = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jBtnLamMoi = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jBtnXemPhieuIn1 = new javax.swing.JPanel();
        jlblIn1 = new javax.swing.JLabel();
        jBtnThem1 = new javax.swing.JPanel();
        jlblThem1 = new javax.swing.JLabel();
        jBtnXoa1 = new javax.swing.JPanel();
        jlblXoa1 = new javax.swing.JLabel();
        jBtnSua1 = new javax.swing.JPanel();
        jlblSua1 = new javax.swing.JLabel();
        jBtnLuu1 = new javax.swing.JPanel();
        jlblLuu1 = new javax.swing.JLabel();
        jBtnHuy1 = new javax.swing.JPanel();
        jlblHuy1 = new javax.swing.JLabel();
        jCheckBoxTimTheoNgay = new javax.swing.JCheckBox();
        jScrDSPT = new javax.swing.JScrollPane();
        jTbDSPT = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jDateTimeTuNgay = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jDateTimeDenNgay = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtxtTimtheoMaPT = new javax.swing.JTextField();
        jPnTracuuPT = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jCbbTimTheoTenKH = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jPnDSPT = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtMaPT = new javax.swing.JTextField();
        jtxtSoTienThu = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtxtLyDoThu = new javax.swing.JTextArea();
        jDCNgayLap = new com.toedter.calendar.JDateChooser();
        jPnThongtinPT = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtMaKH = new javax.swing.JTextField();
        jtxtSDT = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtxtDiaChi = new javax.swing.JTextArea();
        jPnThongtinKH = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCbbTenKH = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jtxtTienNo = new javax.swing.JTextField();
        jtxtTraKH = new javax.swing.JTextField();
        jlblTraKH = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lí phiếu thu");
        setUndecorated(true);
        setSize(new java.awt.Dimension(1366, 728));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnBackMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnBackMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnBackMouseReleased(evt);
            }
        });

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Left_40px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnBackLayout = new javax.swing.GroupLayout(jBtnBack);
        jBtnBack.setLayout(jBtnBackLayout);
        jBtnBackLayout.setHorizontalGroup(
            jBtnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnBackLayout.createSequentialGroup()
                .addComponent(jLabel21)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jBtnBackLayout.setVerticalGroup(
            jBtnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jBtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jBtnXemPhieuIn.setBackground(new java.awt.Color(204, 204, 204));
        jBtnXemPhieuIn.setPreferredSize(new java.awt.Dimension(102, 50));
        jBtnXemPhieuIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnXemPhieuInMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnXemPhieuInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnXemPhieuInMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnXemPhieuInMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnXemPhieuInMouseReleased(evt);
            }
        });

        jlblIn.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlblIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Print_60px_1.png"))); // NOI18N

        javax.swing.GroupLayout jBtnXemPhieuInLayout = new javax.swing.GroupLayout(jBtnXemPhieuIn);
        jBtnXemPhieuIn.setLayout(jBtnXemPhieuInLayout);
        jBtnXemPhieuInLayout.setHorizontalGroup(
            jBtnXemPhieuInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnXemPhieuInLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jlblIn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jBtnXemPhieuInLayout.setVerticalGroup(
            jBtnXemPhieuInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlblIn, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jBtnXemPhieuIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 640, 120, 70));

        jBtnThem.setBackground(new java.awt.Color(204, 204, 204));
        jBtnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnThemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnThemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnThemMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnThemMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnThemMouseReleased(evt);
            }
        });

        jlblThem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Plus_Math_55px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnThemLayout = new javax.swing.GroupLayout(jBtnThem);
        jBtnThem.setLayout(jBtnThemLayout);
        jBtnThemLayout.setHorizontalGroup(
            jBtnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnThemLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jlblThem, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jBtnThemLayout.setVerticalGroup(
            jBtnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlblThem, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jBtnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 640, 120, 70));

        jBtnXoa.setBackground(new java.awt.Color(204, 204, 204));
        jBtnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnXoaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnXoaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnXoaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnXoaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnXoaMouseReleased(evt);
            }
        });

        jlblXoa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Subtract_55px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnXoaLayout = new javax.swing.GroupLayout(jBtnXoa);
        jBtnXoa.setLayout(jBtnXoaLayout);
        jBtnXoaLayout.setHorizontalGroup(
            jBtnXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnXoaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jlblXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jBtnXoaLayout.setVerticalGroup(
            jBtnXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnXoaLayout.createSequentialGroup()
                .addComponent(jlblXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jBtnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 640, 120, -1));

        jBtnSua.setBackground(new java.awt.Color(204, 204, 204));
        jBtnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnSuaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnSuaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnSuaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnSuaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnSuaMouseReleased(evt);
            }
        });

        jlblSua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Edit_48px_1.png"))); // NOI18N

        javax.swing.GroupLayout jBtnSuaLayout = new javax.swing.GroupLayout(jBtnSua);
        jBtnSua.setLayout(jBtnSuaLayout);
        jBtnSuaLayout.setHorizontalGroup(
            jBtnSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnSuaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jlblSua, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jBtnSuaLayout.setVerticalGroup(
            jBtnSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnSuaLayout.createSequentialGroup()
                .addComponent(jlblSua, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jBtnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 640, 120, -1));

        jBtnLuu.setBackground(new java.awt.Color(204, 204, 204));
        jBtnLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLuuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnLuuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnLuuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnLuuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnLuuMouseReleased(evt);
            }
        });

        jlblLuu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Save_55px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnLuuLayout = new javax.swing.GroupLayout(jBtnLuu);
        jBtnLuu.setLayout(jBtnLuuLayout);
        jBtnLuuLayout.setHorizontalGroup(
            jBtnLuuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnLuuLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jlblLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jBtnLuuLayout.setVerticalGroup(
            jBtnLuuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnLuuLayout.createSequentialGroup()
                .addComponent(jlblLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jBtnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 640, 120, -1));

        jBtnHuy.setBackground(new java.awt.Color(204, 204, 204));
        jBtnHuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnHuyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnHuyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnHuyMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnHuyMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnHuyMouseReleased(evt);
            }
        });

        jlblHuy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Reply_Arrow_64px_1.png"))); // NOI18N

        javax.swing.GroupLayout jBtnHuyLayout = new javax.swing.GroupLayout(jBtnHuy);
        jBtnHuy.setLayout(jBtnHuyLayout);
        jBtnHuyLayout.setHorizontalGroup(
            jBtnHuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnHuyLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jlblHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jBtnHuyLayout.setVerticalGroup(
            jBtnHuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnHuyLayout.createSequentialGroup()
                .addComponent(jlblHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jBtnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 640, 120, -1));

        jBtnTimKiem.setBackground(new java.awt.Color(153, 153, 153));
        jBtnTimKiem.setPreferredSize(new java.awt.Dimension(102, 50));
        jBtnTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnTimKiemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnTimKiemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnTimKiemMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnTimKiemMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnTimKiemMouseReleased(evt);
            }
        });

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Search_45px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnTimKiemLayout = new javax.swing.GroupLayout(jBtnTimKiem);
        jBtnTimKiem.setLayout(jBtnTimKiemLayout);
        jBtnTimKiemLayout.setHorizontalGroup(
            jBtnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnTimKiemLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jBtnTimKiemLayout.setVerticalGroup(
            jBtnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jBtnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 110, 120, 60));

        jBtnLamMoi.setBackground(new java.awt.Color(153, 153, 153));
        jBtnLamMoi.setPreferredSize(new java.awt.Dimension(105, 50));
        jBtnLamMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLamMoiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnLamMoiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnLamMoiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnLamMoiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnLamMoiMouseReleased(evt);
            }
        });

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Refresh_45px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnLamMoiLayout = new javax.swing.GroupLayout(jBtnLamMoi);
        jBtnLamMoi.setLayout(jBtnLamMoiLayout);
        jBtnLamMoiLayout.setHorizontalGroup(
            jBtnLamMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnLamMoiLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jBtnLamMoiLayout.setVerticalGroup(
            jBtnLamMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jBtnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 110, 120, 60));

        jBtnXemPhieuIn1.setBackground(new java.awt.Color(204, 204, 204));
        jBtnXemPhieuIn1.setOpaque(false);
        jBtnXemPhieuIn1.setPreferredSize(new java.awt.Dimension(102, 50));
        jBtnXemPhieuIn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnXemPhieuIn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnXemPhieuIn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnXemPhieuIn1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnXemPhieuIn1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnXemPhieuIn1MouseReleased(evt);
            }
        });

        jlblIn1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlblIn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Print_60px_1.png"))); // NOI18N
        jlblIn1.setEnabled(false);

        javax.swing.GroupLayout jBtnXemPhieuIn1Layout = new javax.swing.GroupLayout(jBtnXemPhieuIn1);
        jBtnXemPhieuIn1.setLayout(jBtnXemPhieuIn1Layout);
        jBtnXemPhieuIn1Layout.setHorizontalGroup(
            jBtnXemPhieuIn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnXemPhieuIn1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jlblIn1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jBtnXemPhieuIn1Layout.setVerticalGroup(
            jBtnXemPhieuIn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlblIn1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jBtnXemPhieuIn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 640, 120, 70));

        jBtnThem1.setBackground(new java.awt.Color(204, 204, 204));
        jBtnThem1.setOpaque(false);
        jBtnThem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnThem1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnThem1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnThem1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnThem1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnThem1MouseReleased(evt);
            }
        });

        jlblThem1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblThem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Plus_Math_55px.png"))); // NOI18N
        jlblThem1.setEnabled(false);

        javax.swing.GroupLayout jBtnThem1Layout = new javax.swing.GroupLayout(jBtnThem1);
        jBtnThem1.setLayout(jBtnThem1Layout);
        jBtnThem1Layout.setHorizontalGroup(
            jBtnThem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnThem1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jlblThem1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jBtnThem1Layout.setVerticalGroup(
            jBtnThem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlblThem1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jBtnThem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 640, 120, 70));

        jBtnXoa1.setBackground(new java.awt.Color(204, 204, 204));
        jBtnXoa1.setOpaque(false);
        jBtnXoa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnXoa1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnXoa1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnXoa1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnXoa1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnXoa1MouseReleased(evt);
            }
        });

        jlblXoa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblXoa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Subtract_55px.png"))); // NOI18N
        jlblXoa1.setEnabled(false);

        javax.swing.GroupLayout jBtnXoa1Layout = new javax.swing.GroupLayout(jBtnXoa1);
        jBtnXoa1.setLayout(jBtnXoa1Layout);
        jBtnXoa1Layout.setHorizontalGroup(
            jBtnXoa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnXoa1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jlblXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jBtnXoa1Layout.setVerticalGroup(
            jBtnXoa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnXoa1Layout.createSequentialGroup()
                .addComponent(jlblXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jBtnXoa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 640, 120, -1));

        jBtnSua1.setBackground(new java.awt.Color(204, 204, 204));
        jBtnSua1.setOpaque(false);
        jBtnSua1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnSua1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnSua1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnSua1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnSua1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnSua1MouseReleased(evt);
            }
        });

        jlblSua1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblSua1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Edit_48px_1.png"))); // NOI18N
        jlblSua1.setEnabled(false);

        javax.swing.GroupLayout jBtnSua1Layout = new javax.swing.GroupLayout(jBtnSua1);
        jBtnSua1.setLayout(jBtnSua1Layout);
        jBtnSua1Layout.setHorizontalGroup(
            jBtnSua1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnSua1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jlblSua1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jBtnSua1Layout.setVerticalGroup(
            jBtnSua1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnSua1Layout.createSequentialGroup()
                .addComponent(jlblSua1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jBtnSua1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 640, 120, -1));

        jBtnLuu1.setBackground(new java.awt.Color(204, 204, 204));
        jBtnLuu1.setOpaque(false);
        jBtnLuu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLuu1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnLuu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnLuu1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnLuu1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnLuu1MouseReleased(evt);
            }
        });

        jlblLuu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblLuu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Save_55px.png"))); // NOI18N
        jlblLuu1.setEnabled(false);

        javax.swing.GroupLayout jBtnLuu1Layout = new javax.swing.GroupLayout(jBtnLuu1);
        jBtnLuu1.setLayout(jBtnLuu1Layout);
        jBtnLuu1Layout.setHorizontalGroup(
            jBtnLuu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnLuu1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jlblLuu1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jBtnLuu1Layout.setVerticalGroup(
            jBtnLuu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnLuu1Layout.createSequentialGroup()
                .addComponent(jlblLuu1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jBtnLuu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 640, 120, -1));

        jBtnHuy1.setBackground(new java.awt.Color(204, 204, 204));
        jBtnHuy1.setOpaque(false);
        jBtnHuy1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnHuy1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnHuy1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnHuy1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnHuy1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnHuy1MouseReleased(evt);
            }
        });

        jlblHuy1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblHuy1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Reply_Arrow_64px_1.png"))); // NOI18N
        jlblHuy1.setEnabled(false);

        javax.swing.GroupLayout jBtnHuy1Layout = new javax.swing.GroupLayout(jBtnHuy1);
        jBtnHuy1.setLayout(jBtnHuy1Layout);
        jBtnHuy1Layout.setHorizontalGroup(
            jBtnHuy1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnHuy1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jlblHuy1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jBtnHuy1Layout.setVerticalGroup(
            jBtnHuy1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnHuy1Layout.createSequentialGroup()
                .addComponent(jlblHuy1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jBtnHuy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 640, 120, -1));

        jCheckBoxTimTheoNgay.setText("Tìm theo ngày");
        jCheckBoxTimTheoNgay.setFocusable(false);
        jCheckBoxTimTheoNgay.setOpaque(false);
        jCheckBoxTimTheoNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTimTheoNgayActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxTimTheoNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 132, -1, -1));

        jTbDSPT.setAutoCreateRowSorter(true);
        jTbDSPT.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTbDSPT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu thu", "Tên khách hàng", "Tổng tiền thu", "Ngày thu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTbDSPT.setFocusable(false);
        jTbDSPT.setRowHeight(25);
        jTbDSPT.setSelectionForeground(new java.awt.Color(255, 51, 0));
        jTbDSPT.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTbDSPT.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jTbDSPTMouseDragged(evt);
            }
        });
        jTbDSPT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbDSPTMouseClicked(evt);
            }
        });
        jScrDSPT.setViewportView(jTbDSPT);
        if (jTbDSPT.getColumnModel().getColumnCount() > 0) {
            jTbDSPT.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTbDSPT.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTbDSPT.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTbDSPT.getColumnModel().getColumn(3).setPreferredWidth(120);
        }

        getContentPane().add(jScrDSPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 265, 810, 360));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDateTimeTuNgay.setDateFormatString("dd/MM/yyyy");
        jPanel5.add(jDateTimeTuNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 49, 106, -1));

        jLabel11.setText("Từ ngày :");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 49, -1, 19));

        jLabel12.setText("Đến ngày :");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 49, -1, 20));

        jDateTimeDenNgay.setDateFormatString("dd/MM/yyyy");
        jPanel5.add(jDateTimeDenNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 49, 107, -1));

        jLabel13.setText("Khách hàng :");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 100, -1, -1));

        jLabel14.setText("Mã phiếu thu :");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 133, -1, -1));

        jtxtTimtheoMaPT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtTimtheoMaPTKeyReleased(evt);
            }
        });
        jPanel5.add(jtxtTimtheoMaPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 130, 330, -1));

        jPnTracuuPT.setBackground(new java.awt.Color(0, 204, 204));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Tra cứu phiếu thu:");

        javax.swing.GroupLayout jPnTracuuPTLayout = new javax.swing.GroupLayout(jPnTracuuPT);
        jPnTracuuPT.setLayout(jPnTracuuPTLayout);
        jPnTracuuPTLayout.setHorizontalGroup(
            jPnTracuuPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnTracuuPTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(726, Short.MAX_VALUE))
        );
        jPnTracuuPTLayout.setVerticalGroup(
            jPnTracuuPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel5.add(jPnTracuuPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, -1, -1));

        jCbbTimTheoTenKH.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jCbbTimTheoTenKH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCbbTimTheoTenKH.setFocusable(false);
        jCbbTimTheoTenKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCbbTimTheoTenKHMouseClicked(evt);
            }
        });
        jCbbTimTheoTenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbbTimTheoTenKHActionPerformed(evt);
            }
        });
        jPanel5.add(jCbbTimTheoTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 95, 330, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 820, 160));

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPnDSPT.setBackground(new java.awt.Color(0, 204, 204));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Danh sách phiếu thu:");

        javax.swing.GroupLayout jPnDSPTLayout = new javax.swing.GroupLayout(jPnDSPT);
        jPnDSPT.setLayout(jPnDSPTLayout);
        jPnDSPTLayout.setHorizontalGroup(
            jPnDSPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnDSPTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(726, Short.MAX_VALUE))
        );
        jPnDSPTLayout.setVerticalGroup(
            jPnDSPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel10.add(jPnDSPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 820, 400));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setText("Mã phiếu thu :");

        jLabel7.setText("Ngày lập :");

        jLabel8.setText("Số tiền đã thu :");

        jLabel9.setText("Lý do thu :");

        jtxtMaPT.setEditable(false);
        jtxtMaPT.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N

        jtxtSoTienThu.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jtxtSoTienThu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtSoTienThuKeyReleased(evt);
            }
        });

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jtxtLyDoThu.setColumns(20);
        jtxtLyDoThu.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jtxtLyDoThu.setRows(5);
        jScrollPane3.setViewportView(jtxtLyDoThu);

        jDCNgayLap.setDateFormatString("dd/MM/yyyy");

        jPnThongtinPT.setBackground(new java.awt.Color(0, 204, 204));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Thông tin phiếu thu:");

        javax.swing.GroupLayout jPnThongtinPTLayout = new javax.swing.GroupLayout(jPnThongtinPT);
        jPnThongtinPT.setLayout(jPnThongtinPTLayout);
        jPnThongtinPTLayout.setHorizontalGroup(
            jPnThongtinPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnThongtinPTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(362, Short.MAX_VALUE))
        );
        jPnThongtinPTLayout.setVerticalGroup(
            jPnThongtinPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnThongtinPT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtMaPT)
                    .addComponent(jtxtSoTienThu, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDCNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPnThongtinPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtMaPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDCNgayLap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtxtSoTienThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 420, 500, 290));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Tên khách hàng :");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 64, -1, -1));

        jLabel3.setText("Mã khách hàng :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 113, -1, -1));

        jLabel4.setText("Địa chỉ :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 164, -1, -1));

        jLabel5.setText("Số điện thoại :");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 259, -1, -1));

        jtxtMaKH.setEditable(false);
        jtxtMaKH.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jPanel3.add(jtxtMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 108, 322, -1));

        jtxtSDT.setEditable(false);
        jtxtSDT.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jPanel3.add(jtxtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 254, 322, -1));

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jtxtDiaChi.setEditable(false);
        jtxtDiaChi.setColumns(20);
        jtxtDiaChi.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jtxtDiaChi.setRows(5);
        jScrollPane4.setViewportView(jtxtDiaChi);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 164, 322, 58));

        jPnThongtinKH.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Thông tin khách hàng:");

        javax.swing.GroupLayout jPnThongtinKHLayout = new javax.swing.GroupLayout(jPnThongtinKH);
        jPnThongtinKH.setLayout(jPnThongtinKHLayout);
        jPnThongtinKHLayout.setHorizontalGroup(
            jPnThongtinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnThongtinKHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnThongtinKHLayout.setVerticalGroup(
            jPnThongtinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        jPanel3.add(jPnThongtinKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        jCbbTenKH.setEditable(true);
        jCbbTenKH.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jCbbTenKH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCbbTenKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCbbTenKHMouseClicked(evt);
            }
        });
        jCbbTenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbbTenKHActionPerformed(evt);
            }
        });
        jCbbTenKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCbbTenKHKeyReleased(evt);
            }
        });
        jPanel3.add(jCbbTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 59, 322, -1));

        jLabel18.setText("Số tiền nợ :");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 312, -1, -1));

        jtxtTienNo.setEditable(false);
        jtxtTienNo.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jPanel3.add(jtxtTienNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 307, 322, -1));

        jtxtTraKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtTraKHKeyReleased(evt);
            }
        });
        jPanel3.add(jtxtTraKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 38, 322, -1));

        jlblTraKH.setText("Tra khách hàng :");
        jPanel3.add(jlblTraKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 41, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 60, 500, 350));

        jPanel9.setFocusable(false);
        jPanel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel9MouseDragged(evt);
            }
        });
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel9MousePressed(evt);
            }
        });
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 720));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pexels-photo-530024.jpeg"))); // NOI18N
        jLabel16.setText("jLabel16");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void LoadForm() {
        HienThiDanhSachPhieuThu(CtrlPT.LayDanhSachPhieuThu());
        LoadCbbKH();
        Binding();
        AutoCompleteDecorator.decorate(jCbbTenKH);
        jDateTimeTuNgay.setDate(new Date());
        jDateTimeDenNgay.setDate(new Date());
        CtrlPT.CloseConnection();
        EnableComponent(true);
    }

    public void HienThiDanhSachPhieuThu(ResultSet rs) {
        listPT.clear();
        DefaultTableModel model;
        model = (DefaultTableModel) jTbDSPT.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            while (rs.next()) {
                ObjPhieuThu itemPT;
                itemPT = new ObjPhieuThu(rs.getString("MaPT"), rs.getString("TenKH"), rs.getInt("TienNo"), rs.getInt("TongTienThu"), rs.getTimestamp("NgayThu"), rs.getString("MaKH"), rs.getString("DiaChi"), rs.getString("SDT"), rs.getString("LyDoThu"));
                listPT.add(itemPT);
                Vector v = new Vector();
                v.add(itemPT.getMaPT());
                v.add(itemPT.getTenKH());
                v.add(String.format("%,d", itemPT.getTongTienThu()));
                v.add(dt.format(itemPT.getNgayThu()));
                model.addRow(v);
            }
        } catch (SQLException ex) {
            System.out.println("Ngoại lệ tại FormPhieuThu.HienThiDanhSachPhieuThu: " + ex.getMessage());
        } finally {
            CtrlPT.CloseConnection();
        }
        jTbDSPT.changeSelection(0, 0, false, false);
        Binding();
    }

    public void LoadCbbKH() {
        listCbbKH.clear();
        jCbbTenKH.removeAllItems();
        jCbbTimTheoTenKH.removeAllItems();
        jCbbTenKH.addItem("---Chọn khách hàng---");
        jCbbTimTheoTenKH.addItem("---Chọn khách hàng---");
        listCbbKH.add(new ObjKhachHang());
        try {
            ResultSet rs = CtrlPT.LayDanhSachKhachHang();
            while (rs.next()) {
                jCbbTenKH.addItem(rs.getString("TenKH"));
                jCbbTimTheoTenKH.addItem(rs.getString("TenKH"));
                listCbbKH.add(new ObjKhachHang(rs.getString("MaKH"), rs.getString("TenKH"), rs.getString("SDT"), rs.getString("DiaChi"), rs.getString("Email"), rs.getInt("TienNo")));
            }

        } catch (SQLException ex) {
            System.out.println("Ngoại lệ tại FormPhieuThu.LoadCbbKH: " + ex.getMessage());
        } finally {
            CtrlPT.CloseConnection();
        }
    }

    public void ReloadForm() {
        HienThiDanhSachPhieuThu(CtrlPT.LayDanhSachPhieuThu());
        listPT.clear();
        LoadCbbKH();
        jtxtTimtheoMaPT.setText("");
        jTbDSPT.removeAll();
        jtxtMaPT.setText(CtrlPT.TaoMaPT());
        jDCNgayLap.setDateFormatString("yyyy/MM/dd hh:mm:ss");
        DefaultTableModel model;
        model = (DefaultTableModel) jTbDSPT.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
    }

    public void Binding() {
        if (jTbDSPT.isEnabled()) {
            TableModel model = jTbDSPT.getModel();
            try {
                int viewRow = jTbDSPT.getSelectedRow();
                int modelRow = jTbDSPT.convertRowIndexToModel(viewRow);
                jtxtMaPT.setText(listPT.get(modelRow).getMaPT());
                jDCNgayLap.setDate(listPT.get(modelRow).getNgayThu());
                jtxtSoTienThu.setText(String.format("%,d", listPT.get(modelRow).getTongTienThu()));
                jCbbTenKH.setSelectedItem(listPT.get(modelRow).getTenKH());
                jtxtLyDoThu.setText(listPT.get(modelRow).getLyDoThu());
                jtxtMaKH.setText(listPT.get(modelRow).getMaKH());
                jtxtDiaChi.setText(listPT.get(modelRow).getDiaChi());
                jtxtSDT.setText(listPT.get(modelRow).getSDT());
                jtxtTienNo.setText(String.format("%,d", listPT.get(modelRow).getSoTienNo()));
            } catch (Exception ex) {
                System.out.println("Ngoại lệ tại FormPhieuThu.Binding: " + ex.getMessage());
            }
        }
    }

    private void EnableComponent(boolean Active) {
        jBtnLuu.setVisible(!Active);
        jBtnHuy.setVisible(!Active);
        jlblTraKH.setVisible(!Active);
        jtxtTraKH.setText("");
        jtxtTraKH.setVisible(!Active);
        jCbbTenKH.setEnabled(!Active);

        jTbDSPT.setEnabled(Active);
        jtxtSoTienThu.setEditable(!Active);
        jtxtSoTienThu.setFocusable(!Active);
        jtxtLyDoThu.setEditable(!Active);
        jtxtLyDoThu.setFocusable(!Active);
        jDCNgayLap.setEnabled(!Active);

        jBtnThem.setVisible(Active);
        jBtnXoa.setVisible(Active);
        jBtnSua.setVisible(Active);
        jBtnXemPhieuIn.setVisible(Active);
    }

    private void jBtnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jBtnBackMouseClicked

    private void jBtnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseEntered
        // TODO add your handling code here:
        setColor(jBtnBack);
    }//GEN-LAST:event_jBtnBackMouseEntered

    private void jBtnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseExited
        // TODO add your handling code here:
        resetColor(jBtnBack);
    }//GEN-LAST:event_jBtnBackMouseExited

    private void jBtnBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMousePressed
        // TODO add your handling code here:
        resetColor(jBtnBack);
    }//GEN-LAST:event_jBtnBackMousePressed

    private void jBtnBackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseReleased
        // TODO add your handling code here:
        setColor(jBtnBack);
    }//GEN-LAST:event_jBtnBackMouseReleased

    private void jBtnTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemMouseClicked
        if (jCheckBoxTimTheoNgay.isSelected()) {
            try {
                HienThiDanhSachPhieuThu(CtrlPT.Search(jDateTimeTuNgay.getDate(), jDateTimeDenNgay.getDate(), listCbbKH.get(jCbbTimTheoTenKH.getSelectedIndex()).getMaKH(), jtxtTimtheoMaPT.getText()));
                Binding();
            } catch (Exception ex) {
                System.out.println("Ngoại lệ tại FormQuanLiPhieuThu.jBtnTimKiemMouseClicked:" + ex.getMessage());
            }
        } else {
            try {
                HienThiDanhSachPhieuThu(CtrlPT.Search(listCbbKH.get(jCbbTimTheoTenKH.getSelectedIndex()).getMaKH(), jtxtTimtheoMaPT.getText()));
                Binding();
            } catch (Exception ex) {
                System.out.println("Ngoại lệ tại FormQuanLiPhieuThu.jBtnTimKiemMouseClicked:" + ex.getMessage());
            }
        }

//        try{
//            listPT.clear();
//            DefaultTableModel model = (DefaultTableModel) jTbDSPT.getModel();
//            model.getDataVector().removeAllElements();
//            Vector v = new Vector();
//                    v.add("");
//                    v.add("");
//                    v.add("");
//                    v.add("");
//            model.addRow(v);
//            Resetfield();
//            if(!(jDCTuNgay.getDate()==null && jDCDenNgay.getDate()==null)){
//                if(!jtxtTimtheoKH.getText().equals(""))
//                {
//                    HienThiDanhSachPhieuThu(CtrlPT.Search(jDCTuNgay.getDate(),jDCDenNgay.getDate(),jtxtTimtheoKH.getText()));
//                    Binding();
//                }
//                else{
//                    HienThiDanhSachPhieuThu(CtrlPT.SearchTheoNgay(jDCTuNgay.getDate(),jDCDenNgay.getDate()));
//                    Binding();
//                }             
//            }
//            else{
//                HienThiDanhSachPhieuThu(CtrlPT.SearchTheoText(jtxtTimtheoKH.getText(),jtxtTimtheoMaPT.getText(),jtxtTimtheoLyDoThu.getText()));
//                Binding();
//            }
//        }catch(Exception e){
//            System.out.println("Ngoại lệ tại FormPhieuThu.TimKiem: "+e.getMessage());
//        }

    }//GEN-LAST:event_jBtnTimKiemMouseClicked

    public void Resetfield() { //reset các trường dữ liệu có trên form
        jtxtMaPT.setText("");
        jDCNgayLap.setDate(null);
        jtxtSoTienThu.setText("");
        jtxtLyDoThu.setText("");
        jCbbTenKH.setSelectedIndex(0);
    }
    private void jBtnTimKiemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemMouseEntered
        // TODO add your handling code here:
        setColor(jBtnTimKiem);
    }//GEN-LAST:event_jBtnTimKiemMouseEntered

    private void jBtnTimKiemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemMouseExited
        // TODO add your handling code here:
        resetColor(jBtnTimKiem);
    }//GEN-LAST:event_jBtnTimKiemMouseExited

    private void jBtnTimKiemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemMousePressed
        // TODO add your handling code here:
        resetColor(jBtnTimKiem);
    }//GEN-LAST:event_jBtnTimKiemMousePressed

    private void jBtnTimKiemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemMouseReleased
        // TODO add your handling code here:
        setColor(jBtnTimKiem);
    }//GEN-LAST:event_jBtnTimKiemMouseReleased

    private void jBtnLamMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoiMouseClicked
        // TODO add your handling code here:
        HienThiDanhSachPhieuThu(CtrlPT.LayDanhSachPhieuThu());
        jCheckBoxTimTheoNgay.setSelected(false);
        LoadCbbKH();
        jtxtTimtheoMaPT.setText("");
        jDateTimeTuNgay.setDate(new Date());
        jDateTimeDenNgay.setDate(new Date());
        Binding();
    }//GEN-LAST:event_jBtnLamMoiMouseClicked

    private void jBtnLamMoiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoiMouseEntered
        // TODO add your handling code here:
        setColor(jBtnLamMoi);
    }//GEN-LAST:event_jBtnLamMoiMouseEntered

    private void jBtnLamMoiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoiMouseExited
        // TODO add your handling code here:
        resetColor(jBtnLamMoi);
    }//GEN-LAST:event_jBtnLamMoiMouseExited

    private void jBtnLamMoiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoiMousePressed
        // TODO add your handling code here:
        resetColor(jBtnLamMoi);
    }//GEN-LAST:event_jBtnLamMoiMousePressed

    private void jBtnLamMoiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoiMouseReleased
        // TODO add your handling code here:
        setColor(jBtnLamMoi);
    }//GEN-LAST:event_jBtnLamMoiMouseReleased

    private void jBtnXemPhieuInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemPhieuInMouseClicked
        // TODO add your handling code here:
         try {
            Connect con = new Connect();
            con.Connected();
            HashMap hash = new HashMap();
            InputStream is = null;
            is = new FileInputStream("src/Report/ReportPhieuThu.jasper");
            hash.put("MaPT", jtxtMaPT.getText());
            hash.put("TongTienThuBangChu", conCurrency.numberToString(Double.parseDouble(jtxtSoTienThu.getText().replace(",",""))));
            JasperPrint print = JasperFillManager.fillReport(is, hash, con.getConDB());
            JasperViewer.viewReport(print, false);
        } catch (Exception ex) {
            System.out.println("Ngoại lệ tại FormQuanLiDonDatHang.jBtnXemPhieuInMouseClicked:" + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jBtnXemPhieuInMouseClicked

    private void jBtnXemPhieuInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemPhieuInMouseEntered
        // TODO add your handling code here:
        setColor(jBtnXemPhieuIn);
    }//GEN-LAST:event_jBtnXemPhieuInMouseEntered

    private void jBtnXemPhieuInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemPhieuInMouseExited
        // TODO add your handling code here:
        resetColor(jBtnXemPhieuIn);
    }//GEN-LAST:event_jBtnXemPhieuInMouseExited

    private void jBtnXemPhieuInMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemPhieuInMousePressed
        // TODO add your handling code here:
        resetColor(jBtnXemPhieuIn);
    }//GEN-LAST:event_jBtnXemPhieuInMousePressed

    private void jBtnXemPhieuInMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemPhieuInMouseReleased
        // TODO add your handling code here:
        setColor(jBtnXemPhieuIn);
    }//GEN-LAST:event_jBtnXemPhieuInMouseReleased

    private void jBtnThemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThemMouseEntered
        // TODO add your handling code here:
        setColor(jBtnThem);
    }//GEN-LAST:event_jBtnThemMouseEntered

    private void jBtnThemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThemMouseExited
        // TODO add your handling code here:
        resetColor(jBtnThem);
    }//GEN-LAST:event_jBtnThemMouseExited

    private void jBtnThemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThemMousePressed
        // TODO add your handling code here:
        resetColor(jBtnThem);
    }//GEN-LAST:event_jBtnThemMousePressed

    private void jBtnThemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThemMouseReleased
        // TODO add your handling code here:
        setColor(jBtnThem);
    }//GEN-LAST:event_jBtnThemMouseReleased

    private void jBtnXoaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaMouseEntered
        // TODO add your handling code here:
        setColor(jBtnXoa);
    }//GEN-LAST:event_jBtnXoaMouseEntered

    private void jBtnXoaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaMouseExited
        // TODO add your handling code here:
        resetColor(jBtnXoa);
    }//GEN-LAST:event_jBtnXoaMouseExited

    private void jBtnXoaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaMousePressed
        // TODO add your handling code here:
        resetColor(jBtnXoa);
    }//GEN-LAST:event_jBtnXoaMousePressed

    private void jBtnXoaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaMouseReleased
        // TODO add your handling code here:
        setColor(jBtnXoa);
    }//GEN-LAST:event_jBtnXoaMouseReleased

    private void jBtnSuaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSuaMouseEntered
        // TODO add your handling code here:
        setColor(jBtnSua);
    }//GEN-LAST:event_jBtnSuaMouseEntered

    private void jBtnSuaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSuaMouseExited
        // TODO add your handling code here:
        resetColor(jBtnSua);
    }//GEN-LAST:event_jBtnSuaMouseExited

    private void jBtnSuaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSuaMousePressed
        // TODO add your handling code here:
        resetColor(jBtnSua);
    }//GEN-LAST:event_jBtnSuaMousePressed

    private void jBtnSuaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSuaMouseReleased
        // TODO add your handling code here:
        setColor(jBtnSua);
    }//GEN-LAST:event_jBtnSuaMouseReleased

    private void jBtnLuuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuuMouseEntered
        // TODO add your handling code here:
        setColor(jBtnLuu);
    }//GEN-LAST:event_jBtnLuuMouseEntered

    private void jBtnLuuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuuMouseExited
        // TODO add your handling code here:
        resetColor(jBtnLuu);
    }//GEN-LAST:event_jBtnLuuMouseExited

    private void jBtnLuuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuuMousePressed
        // TODO add your handling code here:
        resetColor(jBtnLuu);
    }//GEN-LAST:event_jBtnLuuMousePressed

    private void jBtnLuuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuuMouseReleased
        // TODO add your handling code here:
        setColor(jBtnLuu);
    }//GEN-LAST:event_jBtnLuuMouseReleased

    private void jBtnHuyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuyMouseEntered
        // TODO add your handling code here:
        setColor(jBtnHuy);
    }//GEN-LAST:event_jBtnHuyMouseEntered

    private void jBtnHuyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuyMouseExited
        // TODO add your handling code here:
        resetColor(jBtnHuy);
    }//GEN-LAST:event_jBtnHuyMouseExited

    private void jBtnHuyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuyMousePressed
        // TODO add your handling code here:
        resetColor(jBtnHuy);
    }//GEN-LAST:event_jBtnHuyMousePressed

    private void jBtnHuyMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuyMouseReleased
        // TODO add your handling code here:
        setColor(jBtnHuy);
    }//GEN-LAST:event_jBtnHuyMouseReleased

    private void jBtnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThemMouseClicked
        // TODO add your handling code here:
        if (jBtnThem.isEnabled()) {
            EnableComponent(false);
            jCbbTenKH.setSelectedIndex(0);
            jtxtMaPT.setText(CtrlPT.TaoMaPT());
            jDCNgayLap.setDate(new Date());
            jtxtSoTienThu.setText("0");
            jtxtLyDoThu.setText("");
            flag = 0;
        }
    }//GEN-LAST:event_jBtnThemMouseClicked

    private void jTbDSPTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbDSPTMouseClicked
        // TODO add your handling code here:
        if (jTbDSPT.getSelectedRow() >= 0 && jTbDSPT.isEnabled()) {
            Binding();
        }
    }//GEN-LAST:event_jTbDSPTMouseClicked

    private void jCbbTenKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCbbTenKHMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbbTenKHMouseClicked

    private void jCbbTenKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbbTenKHActionPerformed
        // TODO add your handling code here:
        try {
            if (jCbbTenKH.isEnabled()) {
                jtxtDiaChi.setText(listCbbKH.get(jCbbTenKH.getSelectedIndex()).getDiaChi());
                jtxtMaKH.setText(listCbbKH.get(jCbbTenKH.getSelectedIndex()).getMaKH());
                jtxtSDT.setText(listCbbKH.get(jCbbTenKH.getSelectedIndex()).getSDT());
                jtxtTienNo.setText(String.format("%,d", listCbbKH.get(jCbbTenKH.getSelectedIndex()).getTienNo()));
            }
        } catch (Exception ex) {
            System.out.println("Ngoại lệ tại FormQuanLiPhieuThu.jCbbTenKHMouseClicked:" + ex.getMessage());
        }
    }//GEN-LAST:event_jCbbTenKHActionPerformed

    private void jBtnHuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuyMouseClicked
        // TODO add your handling code here:
        if (jBtnHuy.isEnabled()) {
            jtxtMaPT.setText("");
            jtxtSoTienThu.setText("");
            jtxtLyDoThu.setText("");
            LoadCbbKH();
            EnableComponent(true);
            flag = 1;
            Binding();
        }
    }//GEN-LAST:event_jBtnHuyMouseClicked

    private void jBtnLuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuuMouseClicked
        // TODO add your handling code here:
        try {
            if (jBtnLuu.isEnabled()) {
                if (flag == 0) {
                    objPT = new ObjPhieuThu(CtrlPT.TaoMaPT(), jtxtLyDoThu.getText(), Integer.parseInt(jtxtSoTienThu.getText().replace(",", "")), jDCNgayLap.getDate(), jtxtMaKH.getText());
                    if (!objPT.getMaKH().equals("")) {
                        try {
                            if (modPT.Insert(objPT)) {
                                JOptionPane.showMessageDialog(this, "Đã lưu.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                                LoadCbbKH();
                                EnableComponent(true);
                                HienThiDanhSachPhieuThu(CtrlPT.LayDanhSachPhieuThu());
                                jTbDSPT.changeSelection(0, 0, false, false);
                                Binding();
                            }
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(this, "Lưu thất bại. Error: " + e.getMessage(), "Thông báo ", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Chưa chọn khách hàng.", "Thông báo ", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    int index = jTbDSPT.getSelectedRow();
                    objPT = new ObjPhieuThu(jtxtMaPT.getText(), jtxtLyDoThu.getText(), Integer.parseInt(jtxtSoTienThu.getText().replace(",", "")), jDCNgayLap.getDate(), jtxtMaKH.getText());
                    if (!objPT.getMaKH().equals("")) {
                        try {
                            if (modPT.Update(objPT)) {
                                JOptionPane.showMessageDialog(this, "Đã lưu.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                                LoadCbbKH();
                                EnableComponent(true);
                                HienThiDanhSachPhieuThu(CtrlPT.LayDanhSachPhieuThu());
                                jTbDSPT.changeSelection(index, 0, false, false);
                                Binding();
                            }
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(this, "Sửa phiếu thu \"" + objPT.getMaPT() + "\" thất bại. Mã: " + e.getMessage(), "Thông báo ", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Chưa chọn khách hàng.", "Thông báo ", JOptionPane.ERROR_MESSAGE);
                    }
                    flag = 0;
                }
            }
        } catch (Exception ex) {
            System.out.println("Error:" + ex.getMessage());
        }
    }//GEN-LAST:event_jBtnLuuMouseClicked

    private void jBtnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSuaMouseClicked
        // TODO add your handling code here:
        if (jBtnSua.isEnabled()) {
            if (CtrlPT.KiemTraPhieuThu(jtxtMaPT.getText(), jtxtMaKH.getText())) {
                EnableComponent(false);
                flag = 1;
            } else {
                JOptionPane.showMessageDialog(this, "Phiếu thu đã cũ không thể chỉnh sửa.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jBtnSuaMouseClicked

    private void jBtnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaMouseClicked
        // TODO add your handling code here:
        if (jBtnXoa.isEnabled()) {
            if (CtrlPT.KiemTraPhieuThu(jtxtMaPT.getText(), jtxtMaKH.getText())) {
                objPT = new ObjPhieuThu(jtxtMaPT.getText());
                int i = JOptionPane.showConfirmDialog(this, "Xác nhận xoá phiếu thu", "Xác nhận", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (i == 0) {
                    try {
                        if (modPT.Delete(objPT.getMaPT())) {
                            JOptionPane.showMessageDialog(this, "Xóa thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                            EnableComponent(true);
                            HienThiDanhSachPhieuThu(CtrlPT.LayDanhSachPhieuThu());
                            LoadCbbKH();
                            Binding();
                        }
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, "Xóa phiếu thu \"" + objPT.getMaPT() + "\" thất bại. Mã lỗi: " + ex.getMessage(), "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Phiếu thu đã cũ không thể xoá.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jBtnXoaMouseClicked

    int xx, yy;

    private void jPanel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_jPanel9MousePressed

    private void jPanel9MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_jPanel9MouseDragged

    private void jBtnXemPhieuIn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemPhieuIn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnXemPhieuIn1MouseClicked

    private void jBtnXemPhieuIn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemPhieuIn1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnXemPhieuIn1MouseEntered

    private void jBtnXemPhieuIn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemPhieuIn1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnXemPhieuIn1MouseExited

    private void jBtnXemPhieuIn1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemPhieuIn1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnXemPhieuIn1MousePressed

    private void jBtnXemPhieuIn1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemPhieuIn1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnXemPhieuIn1MouseReleased

    private void jBtnThem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThem1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnThem1MouseClicked

    private void jBtnThem1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThem1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnThem1MouseEntered

    private void jBtnThem1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThem1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnThem1MouseExited

    private void jBtnThem1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThem1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnThem1MousePressed

    private void jBtnThem1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThem1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnThem1MouseReleased

    private void jBtnXoa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoa1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnXoa1MouseClicked

    private void jBtnXoa1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoa1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnXoa1MouseEntered

    private void jBtnXoa1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoa1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnXoa1MouseExited

    private void jBtnXoa1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoa1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnXoa1MousePressed

    private void jBtnXoa1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoa1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnXoa1MouseReleased

    private void jBtnSua1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSua1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSua1MouseClicked

    private void jBtnSua1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSua1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSua1MouseEntered

    private void jBtnSua1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSua1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSua1MouseExited

    private void jBtnSua1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSua1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSua1MousePressed

    private void jBtnSua1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSua1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSua1MouseReleased

    private void jBtnLuu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuu1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnLuu1MouseClicked

    private void jBtnLuu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuu1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnLuu1MouseEntered

    private void jBtnLuu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuu1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnLuu1MouseExited

    private void jBtnLuu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuu1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnLuu1MousePressed

    private void jBtnLuu1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuu1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnLuu1MouseReleased

    private void jBtnHuy1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuy1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnHuy1MouseClicked

    private void jBtnHuy1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuy1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnHuy1MouseEntered

    private void jBtnHuy1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuy1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnHuy1MouseExited

    private void jBtnHuy1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuy1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnHuy1MousePressed

    private void jBtnHuy1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuy1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnHuy1MouseReleased

    private void jtxtSoTienThuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSoTienThuKeyReleased
        // TODO add your handling code here:
        if (!jtxtSoTienThu.getText().equals("")) {
            try {
                jtxtSoTienThu.setText(String.format("%,d", Integer.parseInt(jtxtSoTienThu.getText().replace(",", ""))));
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Số tiền nhập vào không hợp lệ", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            jtxtSoTienThu.setText("0");
        }
    }//GEN-LAST:event_jtxtSoTienThuKeyReleased

    private void jTbDSPTMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbDSPTMouseDragged
        // TODO add your handling code here:
        if (jTbDSPT.getSelectedRow() >= 0 && jTbDSPT.isEnabled()) {
            Binding();
        }
    }//GEN-LAST:event_jTbDSPTMouseDragged

    private void jCbbTimTheoTenKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCbbTimTheoTenKHMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbbTimTheoTenKHMouseClicked

    private void jCbbTimTheoTenKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbbTimTheoTenKHActionPerformed
        // TODO add your handling code here:
        jBtnTimKiemMouseClicked(null);
    }//GEN-LAST:event_jCbbTimTheoTenKHActionPerformed

    private void jCheckBoxTimTheoNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTimTheoNgayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTimTheoNgayActionPerformed

    private void jtxtTimtheoMaPTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTimtheoMaPTKeyReleased
        // TODO add your handling code here:
        jBtnTimKiemMouseClicked(null);
    }//GEN-LAST:event_jtxtTimtheoMaPTKeyReleased

    private void jCbbTenKHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCbbTenKHKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCbbTenKHKeyReleased

    private void jtxtTraKHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTraKHKeyReleased
        // TODO add your handling code here:
        listCbbKH.clear();
        jCbbTenKH.removeAllItems();
        try {
            ResultSet rs = CtrlPT.TimKhachHang(jtxtTraKH.getText());
            while (rs.next()) {
                jCbbTenKH.addItem(rs.getString("TenKH"));
                jCbbTimTheoTenKH.addItem(rs.getString("TenKH"));
                listCbbKH.add(new ObjKhachHang(rs.getString("MaKH"), rs.getString("TenKH"), rs.getString("SDT"), rs.getString("DiaChi"), rs.getString("Email"), rs.getInt("TienNo")));
            }
            jCbbTenKH.showPopup();
        } catch (SQLException ex) {
            System.out.println("Ngoại lệ tại FormPhieuThu.LoadCbbKH: " + ex.getMessage());
        } finally {
            CtrlPT.CloseConnection();
        }
    }//GEN-LAST:event_jtxtTraKHKeyReleased

    public void setColor(JPanel pn) {
        if (pn.isEnabled()) {
            pn.setSize(pn.getWidth() + 1, pn.getHeight() + 1);
            pn.setBackground(new Color(60, 209, 127, 50));
        }
    }

    public void resetColor(JPanel pn) {
        if (pn.isEnabled()) {
            pn.setSize(pn.getWidth() - 1, pn.getHeight() - 1);
            pn.setBackground(new Color(153, 153, 153, 180));
        }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQuanLiPhieuThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQuanLiPhieuThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQuanLiPhieuThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQuanLiPhieuThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQuanLiPhieuThu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBtnBack;
    private javax.swing.JPanel jBtnHuy;
    private javax.swing.JPanel jBtnHuy1;
    private javax.swing.JPanel jBtnLamMoi;
    private javax.swing.JPanel jBtnLuu;
    private javax.swing.JPanel jBtnLuu1;
    private javax.swing.JPanel jBtnSua;
    private javax.swing.JPanel jBtnSua1;
    private javax.swing.JPanel jBtnThem;
    private javax.swing.JPanel jBtnThem1;
    private javax.swing.JPanel jBtnTimKiem;
    private javax.swing.JPanel jBtnXemPhieuIn;
    private javax.swing.JPanel jBtnXemPhieuIn1;
    private javax.swing.JPanel jBtnXoa;
    private javax.swing.JPanel jBtnXoa1;
    private javax.swing.JComboBox<String> jCbbTenKH;
    private javax.swing.JComboBox<String> jCbbTimTheoTenKH;
    private javax.swing.JCheckBox jCheckBoxTimTheoNgay;
    private com.toedter.calendar.JDateChooser jDCNgayLap;
    private com.toedter.calendar.JDateChooser jDateTimeDenNgay;
    private com.toedter.calendar.JDateChooser jDateTimeTuNgay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPnDSPT;
    private javax.swing.JPanel jPnThongtinKH;
    private javax.swing.JPanel jPnThongtinPT;
    private javax.swing.JPanel jPnTracuuPT;
    private javax.swing.JScrollPane jScrDSPT;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTbDSPT;
    private javax.swing.JLabel jlblHuy;
    private javax.swing.JLabel jlblHuy1;
    private javax.swing.JLabel jlblIn;
    private javax.swing.JLabel jlblIn1;
    private javax.swing.JLabel jlblLuu;
    private javax.swing.JLabel jlblLuu1;
    private javax.swing.JLabel jlblSua;
    private javax.swing.JLabel jlblSua1;
    private javax.swing.JLabel jlblThem;
    private javax.swing.JLabel jlblThem1;
    private javax.swing.JLabel jlblTraKH;
    private javax.swing.JLabel jlblXoa;
    private javax.swing.JLabel jlblXoa1;
    private javax.swing.JTextArea jtxtDiaChi;
    private javax.swing.JTextArea jtxtLyDoThu;
    private javax.swing.JTextField jtxtMaKH;
    private javax.swing.JTextField jtxtMaPT;
    private javax.swing.JTextField jtxtSDT;
    private javax.swing.JTextField jtxtSoTienThu;
    private javax.swing.JTextField jtxtTienNo;
    private javax.swing.JTextField jtxtTimtheoMaPT;
    private javax.swing.JTextField jtxtTraKH;
    // End of variables declaration//GEN-END:variables
}


