/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.CtrlKhachHang;
import Edit.Edit;
import Model.ModKhachHang;
import Object.ObjKhachHang;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Thanh
 */
public class FormQuanLiKhachHang extends javax.swing.JFrame {

    Edit editFrm = new Edit();
    ArrayList<ObjKhachHang> listKH = new ArrayList<>();
    CtrlKhachHang CtrlKH = new CtrlKhachHang();
    ObjKhachHang ObjKH = new ObjKhachHang();
    ModKhachHang ModKH = new ModKhachHang();
    private int flag = 0;

    /**
     * Creates new form FormQuanLiKhachHang
     */
    public FormQuanLiKhachHang() {
        initComponents();
        setLocationRelativeTo(null);
        jPanel1.setBackground(new Color(0, 0, 0, 0));

        JPanel ListPanel[] = new JPanel[]{jPanel2, jPanel3, jPanel4};
        editFrm.MakeTransparentPanel(ListPanel);

        JPanel ListTitle[] = new JPanel[]{jPnDSKH, jPnThongtinKH, jPnTracuuKH};
        editFrm.MakeTransparentTitle(ListTitle);

        JPanel ListButton[] = new JPanel[]{jBtnBack, jBtnHuy, jBtnLamMoi, jBtnLuu, jBtnSua, jBtnThem, jBtnTimKiem, jBtnXoa};
        editFrm.MakeTransparentButton(ListButton);

        editFrm.MakeTransparentTable(jScrDSKH, jtbDSKH);
        jtxtDiaChi.setLineWrap(true);
        LoadForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnBack = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jBtnThem = new javax.swing.JPanel();
        jlblThem = new javax.swing.JLabel();
        jBtnXoa = new javax.swing.JPanel();
        jlblXoa = new javax.swing.JLabel();
        jBtnSua = new javax.swing.JPanel();
        jlblSua = new javax.swing.JLabel();
        jBtnLuu = new javax.swing.JPanel();
        jlblLuu = new javax.swing.JLabel();
        jBtnHuy = new javax.swing.JPanel();
        jlblHuy = new javax.swing.JLabel();
        jBtnThem1 = new javax.swing.JPanel();
        jlblThem1 = new javax.swing.JLabel();
        jBtnXoa1 = new javax.swing.JPanel();
        jlblXoa1 = new javax.swing.JLabel();
        jBtnSua1 = new javax.swing.JPanel();
        jlblSua1 = new javax.swing.JLabel();
        jBtnLuu1 = new javax.swing.JPanel();
        jlblLuu1 = new javax.swing.JLabel();
        jBtnHuy1 = new javax.swing.JPanel();
        jlblHuy1 = new javax.swing.JLabel();
        jBtnLamMoi = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jBtnTimKiem = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrDSKH = new javax.swing.JScrollPane();
        jtbDSKH = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jcbbTimTheo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jtxtTimKiem = new javax.swing.JTextField();
        jPnTracuuKH = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPnDSKH = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtSDT = new javax.swing.JTextField();
        jtxtTenKH = new javax.swing.JTextField();
        jtxtMaKH = new javax.swing.JTextField();
        jtxtEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtDiaChi = new javax.swing.JTextArea();
        jPnThongtinKH = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtxtTienNo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnBackMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnBackMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnBackMouseReleased(evt);
            }
        });

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Left_40px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnBackLayout = new javax.swing.GroupLayout(jBtnBack);
        jBtnBack.setLayout(jBtnBackLayout);
        jBtnBackLayout.setHorizontalGroup(
            jBtnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnBackLayout.createSequentialGroup()
                .addComponent(jLabel21)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jBtnBackLayout.setVerticalGroup(
            jBtnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jBtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jBtnThem.setBackground(new java.awt.Color(204, 204, 204));
        jBtnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnThemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnThemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnThemMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnThemMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnThemMouseReleased(evt);
            }
        });

        jlblThem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Plus_Math_55px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnThemLayout = new javax.swing.GroupLayout(jBtnThem);
        jBtnThem.setLayout(jBtnThemLayout);
        jBtnThemLayout.setHorizontalGroup(
            jBtnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnThemLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jlblThem)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jBtnThemLayout.setVerticalGroup(
            jBtnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnThemLayout.createSequentialGroup()
                .addComponent(jlblThem, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jBtnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 100, 70));

        jBtnXoa.setBackground(new java.awt.Color(204, 204, 204));
        jBtnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnXoaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnXoaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnXoaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnXoaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnXoaMouseReleased(evt);
            }
        });

        jlblXoa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Subtract_55px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnXoaLayout = new javax.swing.GroupLayout(jBtnXoa);
        jBtnXoa.setLayout(jBtnXoaLayout);
        jBtnXoaLayout.setHorizontalGroup(
            jBtnXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnXoaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jlblXoa)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jBtnXoaLayout.setVerticalGroup(
            jBtnXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnXoaLayout.createSequentialGroup()
                .addComponent(jlblXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jBtnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 640, 100, 70));

        jBtnSua.setBackground(new java.awt.Color(204, 204, 204));
        jBtnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnSuaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnSuaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnSuaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnSuaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnSuaMouseReleased(evt);
            }
        });

        jlblSua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Edit_48px_1.png"))); // NOI18N

        javax.swing.GroupLayout jBtnSuaLayout = new javax.swing.GroupLayout(jBtnSua);
        jBtnSua.setLayout(jBtnSuaLayout);
        jBtnSuaLayout.setHorizontalGroup(
            jBtnSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnSuaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlblSua, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jBtnSuaLayout.setVerticalGroup(
            jBtnSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnSuaLayout.createSequentialGroup()
                .addComponent(jlblSua, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jBtnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 640, 100, 70));

        jBtnLuu.setBackground(new java.awt.Color(204, 204, 204));
        jBtnLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLuuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnLuuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnLuuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnLuuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnLuuMouseReleased(evt);
            }
        });

        jlblLuu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Save_55px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnLuuLayout = new javax.swing.GroupLayout(jBtnLuu);
        jBtnLuu.setLayout(jBtnLuuLayout);
        jBtnLuuLayout.setHorizontalGroup(
            jBtnLuuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnLuuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jlblLuu)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jBtnLuuLayout.setVerticalGroup(
            jBtnLuuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnLuuLayout.createSequentialGroup()
                .addComponent(jlblLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jBtnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 640, 100, 70));

        jBtnHuy.setBackground(new java.awt.Color(204, 204, 204));
        jBtnHuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnHuyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnHuyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnHuyMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnHuyMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnHuyMouseReleased(evt);
            }
        });

        jlblHuy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Reply_Arrow_64px_1.png"))); // NOI18N

        javax.swing.GroupLayout jBtnHuyLayout = new javax.swing.GroupLayout(jBtnHuy);
        jBtnHuy.setLayout(jBtnHuyLayout);
        jBtnHuyLayout.setHorizontalGroup(
            jBtnHuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnHuyLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jlblHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jBtnHuyLayout.setVerticalGroup(
            jBtnHuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnHuyLayout.createSequentialGroup()
                .addComponent(jlblHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jBtnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 640, 100, 70));

        jBtnThem1.setBackground(new java.awt.Color(204, 204, 204));
        jBtnThem1.setOpaque(false);
        jBtnThem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnThem1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnThem1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnThem1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnThem1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnThem1MouseReleased(evt);
            }
        });

        jlblThem1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblThem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Plus_Math_55px.png"))); // NOI18N
        jlblThem1.setEnabled(false);

        javax.swing.GroupLayout jBtnThem1Layout = new javax.swing.GroupLayout(jBtnThem1);
        jBtnThem1.setLayout(jBtnThem1Layout);
        jBtnThem1Layout.setHorizontalGroup(
            jBtnThem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnThem1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jlblThem1)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jBtnThem1Layout.setVerticalGroup(
            jBtnThem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnThem1Layout.createSequentialGroup()
                .addComponent(jlblThem1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jBtnThem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 100, 70));

        jBtnXoa1.setBackground(new java.awt.Color(204, 204, 204));
        jBtnXoa1.setOpaque(false);
        jBtnXoa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnXoa1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnXoa1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnXoa1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnXoa1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnXoa1MouseReleased(evt);
            }
        });

        jlblXoa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblXoa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Subtract_55px.png"))); // NOI18N
        jlblXoa1.setEnabled(false);

        javax.swing.GroupLayout jBtnXoa1Layout = new javax.swing.GroupLayout(jBtnXoa1);
        jBtnXoa1.setLayout(jBtnXoa1Layout);
        jBtnXoa1Layout.setHorizontalGroup(
            jBtnXoa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnXoa1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jlblXoa1)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jBtnXoa1Layout.setVerticalGroup(
            jBtnXoa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnXoa1Layout.createSequentialGroup()
                .addComponent(jlblXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jBtnXoa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 640, 100, 70));

        jBtnSua1.setBackground(new java.awt.Color(204, 204, 204));
        jBtnSua1.setOpaque(false);
        jBtnSua1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnSua1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnSua1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnSua1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnSua1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnSua1MouseReleased(evt);
            }
        });

        jlblSua1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblSua1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Edit_48px_1.png"))); // NOI18N
        jlblSua1.setEnabled(false);

        javax.swing.GroupLayout jBtnSua1Layout = new javax.swing.GroupLayout(jBtnSua1);
        jBtnSua1.setLayout(jBtnSua1Layout);
        jBtnSua1Layout.setHorizontalGroup(
            jBtnSua1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnSua1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlblSua1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jBtnSua1Layout.setVerticalGroup(
            jBtnSua1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnSua1Layout.createSequentialGroup()
                .addComponent(jlblSua1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jBtnSua1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 640, 100, 70));

        jBtnLuu1.setBackground(new java.awt.Color(204, 204, 204));
        jBtnLuu1.setOpaque(false);
        jBtnLuu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLuu1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnLuu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnLuu1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnLuu1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnLuu1MouseReleased(evt);
            }
        });

        jlblLuu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblLuu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Save_55px.png"))); // NOI18N
        jlblLuu1.setEnabled(false);

        javax.swing.GroupLayout jBtnLuu1Layout = new javax.swing.GroupLayout(jBtnLuu1);
        jBtnLuu1.setLayout(jBtnLuu1Layout);
        jBtnLuu1Layout.setHorizontalGroup(
            jBtnLuu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnLuu1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jlblLuu1)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jBtnLuu1Layout.setVerticalGroup(
            jBtnLuu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnLuu1Layout.createSequentialGroup()
                .addComponent(jlblLuu1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jBtnLuu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 640, 100, 70));

        jBtnHuy1.setBackground(new java.awt.Color(204, 204, 204));
        jBtnHuy1.setOpaque(false);
        jBtnHuy1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnHuy1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnHuy1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnHuy1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnHuy1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnHuy1MouseReleased(evt);
            }
        });

        jlblHuy1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblHuy1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Reply_Arrow_64px_1.png"))); // NOI18N
        jlblHuy1.setEnabled(false);

        javax.swing.GroupLayout jBtnHuy1Layout = new javax.swing.GroupLayout(jBtnHuy1);
        jBtnHuy1.setLayout(jBtnHuy1Layout);
        jBtnHuy1Layout.setHorizontalGroup(
            jBtnHuy1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnHuy1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jlblHuy1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jBtnHuy1Layout.setVerticalGroup(
            jBtnHuy1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnHuy1Layout.createSequentialGroup()
                .addComponent(jlblHuy1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jBtnHuy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 640, 100, 70));

        jBtnLamMoi.setBackground(new java.awt.Color(204, 204, 204));
        jBtnLamMoi.setPreferredSize(new java.awt.Dimension(105, 50));
        jBtnLamMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLamMoiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnLamMoiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnLamMoiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnLamMoiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnLamMoiMouseReleased(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Refresh_45px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnLamMoiLayout = new javax.swing.GroupLayout(jBtnLamMoi);
        jBtnLamMoi.setLayout(jBtnLamMoiLayout);
        jBtnLamMoiLayout.setHorizontalGroup(
            jBtnLamMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBtnLamMoiLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(37, 37, 37))
        );
        jBtnLamMoiLayout.setVerticalGroup(
            jBtnLamMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        getContentPane().add(jBtnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 95, 120, 65));

        jBtnTimKiem.setBackground(new java.awt.Color(204, 204, 204));
        jBtnTimKiem.setPreferredSize(new java.awt.Dimension(102, 50));
        jBtnTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnTimKiemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnTimKiemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnTimKiemMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnTimKiemMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnTimKiemMouseReleased(evt);
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Search_45px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnTimKiemLayout = new javax.swing.GroupLayout(jBtnTimKiem);
        jBtnTimKiem.setLayout(jBtnTimKiemLayout);
        jBtnTimKiemLayout.setHorizontalGroup(
            jBtnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnTimKiemLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jBtnTimKiemLayout.setVerticalGroup(
            jBtnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        getContentPane().add(jBtnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 95, 120, 65));

        jtbDSKH.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jtbDSKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Tên khách hàng", "Số điệnt thoại", "Tiền nợ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbDSKH.setFocusable(false);
        jtbDSKH.setRowHeight(25);
        jtbDSKH.setSelectionForeground(new java.awt.Color(255, 51, 0));
        jtbDSKH.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtbDSKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbDSKHMouseClicked(evt);
            }
        });
        jScrDSKH.setViewportView(jtbDSKH);
        if (jtbDSKH.getColumnModel().getColumnCount() > 0) {
            jtbDSKH.getColumnModel().getColumn(0).setPreferredWidth(80);
            jtbDSKH.getColumnModel().getColumn(1).setPreferredWidth(200);
            jtbDSKH.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        getContentPane().add(jScrDSKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 224, 780, 480));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Tra cứu khách hàng :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel10.setText("Tìm theo :");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 53, -1, -1));

        jcbbTimTheo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tên khách hàng", "Mã khách hàng", "Địa chỉ", "Số điện thoại", "Email" }));
        jcbbTimTheo.setFocusable(false);
        jPanel3.add(jcbbTimTheo, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 50, 184, -1));

        jLabel11.setText("Từ tìm kiếm :");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 91, -1, -1));

        jtxtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtTimKiemKeyReleased(evt);
            }
        });
        jPanel3.add(jtxtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 88, 340, -1));

        jPnTracuuKH.setBackground(new java.awt.Color(0, 204, 255));

        javax.swing.GroupLayout jPnTracuuKHLayout = new javax.swing.GroupLayout(jPnTracuuKH);
        jPnTracuuKH.setLayout(jPnTracuuKHLayout);
        jPnTracuuKHLayout.setHorizontalGroup(
            jPnTracuuKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jPnTracuuKHLayout.setVerticalGroup(
            jPnTracuuKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jPanel3.add(jPnTracuuKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 37));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 790, 120));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        jPnDSKH.setBackground(new java.awt.Color(0, 204, 255));
        jPnDSKH.setPreferredSize(new java.awt.Dimension(790, 37));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Danh sách khách hàng :");

        javax.swing.GroupLayout jPnDSKHLayout = new javax.swing.GroupLayout(jPnDSKH);
        jPnDSKH.setLayout(jPnDSKHLayout);
        jPnDSKHLayout.setHorizontalGroup(
            jPnDSKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnDSKHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(634, Short.MAX_VALUE))
        );
        jPnDSKHLayout.setVerticalGroup(
            jPnDSKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnDSKHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPnDSKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPnDSKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(493, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 790, 530));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel5.setText("Mã khách hàng :");

        jLabel6.setText("Tên khách hàng :");

        jLabel7.setText("Số điện thoại :");

        jLabel8.setText("Địa chỉ :");

        jLabel9.setText("Email :");

        jtxtSDT.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N

        jtxtTenKH.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N

        jtxtMaKH.setEditable(false);
        jtxtMaKH.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N

        jtxtEmail.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jtxtDiaChi.setColumns(20);
        jtxtDiaChi.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jtxtDiaChi.setRows(5);
        jScrollPane1.setViewportView(jtxtDiaChi);

        jPnThongtinKH.setBackground(new java.awt.Color(0, 204, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Thông tin khách hàng :");

        javax.swing.GroupLayout jPnThongtinKHLayout = new javax.swing.GroupLayout(jPnThongtinKH);
        jPnThongtinKH.setLayout(jPnThongtinKHLayout);
        jPnThongtinKHLayout.setHorizontalGroup(
            jPnThongtinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnThongtinKHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(387, Short.MAX_VALUE))
        );
        jPnThongtinKHLayout.setVerticalGroup(
            jPnThongtinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnThongtinKHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel14.setText("Tiền nợ :");

        jtxtTienNo.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnThongtinKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(41, 41, 41))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(44, 44, 44))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(52, 52, 52))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel7))
                            .addGap(4, 4, 4))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtxtTienNo, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtTenKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPnThongtinKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(jtxtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7))
                    .addComponent(jtxtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel9))
                    .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtTienNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 540, 580));

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 720));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pexels-photo-459654.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jBtnBackMouseClicked

    private void jBtnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseEntered
        // TODO add your handling code here:
        setColor(jBtnBack);
    }//GEN-LAST:event_jBtnBackMouseEntered

    private void jBtnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseExited
        // TODO add your handling code here:
        resetColor(jBtnBack);
    }//GEN-LAST:event_jBtnBackMouseExited

    private void jBtnBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMousePressed
        // TODO add your handling code here:
        resetColor(jBtnBack);
    }//GEN-LAST:event_jBtnBackMousePressed

    private void jBtnBackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseReleased
        // TODO add your handling code here:
        setColor(jBtnBack);
    }//GEN-LAST:event_jBtnBackMouseReleased

    private void jBtnLamMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoiMouseClicked
        // TODO add your handling code here:
        //        try {
        //            // TODO add your handling code here:
        //            ResultSet rs =BSP.searchByPropertiesWithFulltext(jtxtTimKiemMaSP.getText(),jtxtTimKiemTenSP.getText(),jCbbLoaiSP.getSelectedItem().toString());
        //            if(rs.getRow()==0){
        //                rs =BSP.searchByPropertiesNormal(jtxtTimKiemMaSP.getText(),jtxtTimKiemTenSP.getText(),jCbbLoaiSP.getSelectedItem().toString());
        //            }
        //            displayData(rs);
        //            Binding();
        //        } catch (SQLException ex) {
        //            Logger.getLogger(FrmQuanLiSanPham.class.getName()).log(Level.SEVERE, null, ex);
        //        }
        HienThiDanhSachKhachHang(CtrlKH.LayDanhSachKhachHang());
        jtxtTimKiem.setText("");
    }//GEN-LAST:event_jBtnLamMoiMouseClicked

    private void jBtnLamMoiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoiMouseEntered
        // TODO add your handling code here:
        setColor(jBtnLamMoi);
    }//GEN-LAST:event_jBtnLamMoiMouseEntered

    private void jBtnLamMoiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoiMouseExited
        // TODO add your handling code here:
        resetColor(jBtnLamMoi);
    }//GEN-LAST:event_jBtnLamMoiMouseExited

    private void jBtnLamMoiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoiMousePressed
        // TODO add your handling code here:
        resetColor(jBtnLamMoi);
    }//GEN-LAST:event_jBtnLamMoiMousePressed

    private void jBtnLamMoiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoiMouseReleased
        // TODO add your handling code here:
        setColor(jBtnLamMoi);
    }//GEN-LAST:event_jBtnLamMoiMouseReleased

    private void jBtnTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemMouseClicked
        if (jcbbTimTheo.getSelectedIndex() == 0) {
            HienThiDanhSachKhachHang(CtrlKH.SearchKhachHangByName(jtxtTimKiem.getText()));
        } else if (jcbbTimTheo.getSelectedIndex() == 1) {
            HienThiDanhSachKhachHang(CtrlKH.SearchKhachHangByID(jtxtTimKiem.getText()));
        } else if (jcbbTimTheo.getSelectedIndex() == 2) {
            HienThiDanhSachKhachHang(CtrlKH.SearchKhachHangByDiaChi(jtxtTimKiem.getText()));
        } else if (jcbbTimTheo.getSelectedIndex() == 3) {
            HienThiDanhSachKhachHang(CtrlKH.SearchKhachHangBySDT(jtxtTimKiem.getText()));
        } else {
            HienThiDanhSachKhachHang(CtrlKH.SearchKhachHangBySDT(jtxtTimKiem.getText()));
        }
        Binding();
    }//GEN-LAST:event_jBtnTimKiemMouseClicked

    private void jBtnTimKiemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemMouseEntered
        // TODO add your handling code here:
        setColor(jBtnTimKiem);
    }//GEN-LAST:event_jBtnTimKiemMouseEntered

    private void jBtnTimKiemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemMouseExited
        // TODO add your handling code here:
        resetColor(jBtnTimKiem);
    }//GEN-LAST:event_jBtnTimKiemMouseExited

    private void jBtnTimKiemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemMousePressed
        // TODO add your handling code here:
        resetColor(jBtnTimKiem);
    }//GEN-LAST:event_jBtnTimKiemMousePressed

    private void jBtnTimKiemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemMouseReleased
        // TODO add your handling code here:
        setColor(jBtnTimKiem);
    }//GEN-LAST:event_jBtnTimKiemMouseReleased

    private void jBtnThemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThemMouseEntered
        // TODO add your handling code here:
        setColor(jBtnThem);
    }//GEN-LAST:event_jBtnThemMouseEntered

    private void jBtnThemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThemMouseExited
        // TODO add your handling code here:
        resetColor(jBtnThem);
    }//GEN-LAST:event_jBtnThemMouseExited

    private void jBtnThemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThemMousePressed
        // TODO add your handling code here:
        resetColor(jBtnThem);
    }//GEN-LAST:event_jBtnThemMousePressed

    private void jBtnThemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThemMouseReleased
        // TODO add your handling code here:
        setColor(jBtnThem);
    }//GEN-LAST:event_jBtnThemMouseReleased

    private void jBtnXoaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaMouseEntered
        // TODO add your handling code here:
        setColor(jBtnXoa);
    }//GEN-LAST:event_jBtnXoaMouseEntered

    private void jBtnXoaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaMouseExited
        // TODO add your handling code here:
        resetColor(jBtnXoa);
    }//GEN-LAST:event_jBtnXoaMouseExited

    private void jBtnXoaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaMousePressed
        // TODO add your handling code here:
        resetColor(jBtnXoa);
    }//GEN-LAST:event_jBtnXoaMousePressed

    private void jBtnXoaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaMouseReleased
        // TODO add your handling code here:
        setColor(jBtnXoa);
    }//GEN-LAST:event_jBtnXoaMouseReleased

    private void jBtnSuaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSuaMouseEntered
        // TODO add your handling code here:
        setColor(jBtnSua);
    }//GEN-LAST:event_jBtnSuaMouseEntered

    private void jBtnSuaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSuaMouseExited
        // TODO add your handling code here:
        resetColor(jBtnSua);
    }//GEN-LAST:event_jBtnSuaMouseExited

    private void jBtnSuaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSuaMousePressed
        // TODO add your handling code here:
        resetColor(jBtnSua);
    }//GEN-LAST:event_jBtnSuaMousePressed

    private void jBtnSuaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSuaMouseReleased
        // TODO add your handling code here:
        setColor(jBtnSua);
    }//GEN-LAST:event_jBtnSuaMouseReleased

    private void jBtnLuuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuuMouseEntered
        // TODO add your handling code here:
        setColor(jBtnLuu);
    }//GEN-LAST:event_jBtnLuuMouseEntered

    private void jBtnLuuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuuMouseExited
        // TODO add your handling code here:
        resetColor(jBtnLuu);
    }//GEN-LAST:event_jBtnLuuMouseExited

    private void jBtnLuuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuuMousePressed
        // TODO add your handling code here:
        resetColor(jBtnLuu);
    }//GEN-LAST:event_jBtnLuuMousePressed

    private void jBtnLuuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuuMouseReleased
        // TODO add your handling code here:
        setColor(jBtnLuu);
    }//GEN-LAST:event_jBtnLuuMouseReleased

    private void jBtnHuyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuyMouseEntered
        // TODO add your handling code here:
        setColor(jBtnHuy);
    }//GEN-LAST:event_jBtnHuyMouseEntered

    private void jBtnHuyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuyMouseExited
        // TODO add your handling code here:
        resetColor(jBtnHuy);
    }//GEN-LAST:event_jBtnHuyMouseExited

    private void jBtnHuyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuyMousePressed
        // TODO add your handling code here:
        resetColor(jBtnHuy);
    }//GEN-LAST:event_jBtnHuyMousePressed

    private void jBtnHuyMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuyMouseReleased
        // TODO add your handling code here:
        setColor(jBtnHuy);
    }//GEN-LAST:event_jBtnHuyMouseReleased

    private void jtbDSKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbDSKHMouseClicked
        // TODO add your handling code here:
        if (jtbDSKH.isEnabled()) {
            Binding();
        }
    }//GEN-LAST:event_jtbDSKHMouseClicked

    private void jBtnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaMouseClicked
        // TODO add your handling code here:
        if (jBtnXoa.isEnabled()) {
            ObjKH = new ObjKhachHang(jtxtMaKH.getText(), jtxtTenKH.getText(), jtxtSDT.getText(), jtxtDiaChi.getText(), jtxtEmail.getText(), Integer.parseInt(jtxtTienNo.getText().replace(",", "")));
            int i = JOptionPane.showConfirmDialog(this, "Bạn muốn xóa khách hàng ?", "Xác nhận", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (i == 0) {
                try {
                    if (ModKH.Delete(ObjKH.getMaKH())) {
                        JOptionPane.showMessageDialog(this, "Xóa khách hàng thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                        HienThiDanhSachKhachHang(CtrlKH.LayDanhSachKhachHang());
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Xóa khách hàng thất bại. Lỗi: " + ex.getMessage(), "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jBtnXoaMouseClicked

    private void jBtnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThemMouseClicked
        // TODO add your handling code here:
        if (jBtnThem.isEnabled()) {
            jtxtMaKH.setText(CtrlKH.TaoMaKH());
            jtxtTenKH.setText("");
            jtxtSDT.setText("");
            jtxtDiaChi.setText("");
            jtxtEmail.setText("");
            jtxtTienNo.setText("");
            jtxtTienNo.setText("0");
            EnableComponent(false);
            flag = 1;
        }
    }//GEN-LAST:event_jBtnThemMouseClicked

    private void jBtnHuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuyMouseClicked
        // TODO add your handling code here:
        if (jBtnHuy.isEnabled()) {
            jtxtMaKH.setText("");
            jtxtTenKH.setText("");
            jtxtSDT.setText("");
            jtxtDiaChi.setText("");
            jtxtEmail.setText("");
            EnableComponent(true);
            flag = 0;
        }
    }//GEN-LAST:event_jBtnHuyMouseClicked

    private void jBtnLuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuuMouseClicked
        // TODO add your handling code here:
        if (jBtnLuu.isEnabled()) {
            try {
                ObjKH = new ObjKhachHang(jtxtMaKH.getText(), jtxtTenKH.getText(), jtxtSDT.getText(), jtxtDiaChi.getText(), jtxtEmail.getText(), Integer.parseInt(jtxtTienNo.getText()));
                if (!ObjKH.getTenKH().equals("")) {
                    if (flag == 1) {
                        if (ModKH.Insert(ObjKH)) {
                            EnableComponent(true);
                            JOptionPane.showMessageDialog(this, "Thêm khách hàng thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                            HienThiDanhSachKhachHang(CtrlKH.LayDanhSachKhachHang());
                        } else {
                            JOptionPane.showMessageDialog(this, "Thêm khách thất bại.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                        }
                    } else {
                        if (ModKH.Update(ObjKH)) {
                            EnableComponent(true);
                            JOptionPane.showMessageDialog(this, "Cập nhật thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                            HienThiDanhSachKhachHang(CtrlKH.LayDanhSachKhachHang());
                        } else {
                            JOptionPane.showMessageDialog(this, "Cập nhật thất bại.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Tên khách hàng không được để trống.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception ex) {
                System.out.println("Ngoại lệ tại FormQuanLiKhachHang.jBtnLuuMouseClicked:" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_jBtnLuuMouseClicked

    private void jBtnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSuaMouseClicked
        // TODO add your handling code here:
        if (jBtnSua.isEnabled()) {
            EnableComponent(false);
            flag = 0;
            jtxtTienNo.setText(jtxtTienNo.getText().replace(",", ""));
        }
    }//GEN-LAST:event_jBtnSuaMouseClicked

    int xx, yy;

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jBtnThem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThem1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnThem1MouseClicked

    private void jBtnThem1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThem1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnThem1MouseEntered

    private void jBtnThem1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThem1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnThem1MouseExited

    private void jBtnThem1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThem1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnThem1MousePressed

    private void jBtnThem1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThem1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnThem1MouseReleased

    private void jBtnXoa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoa1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnXoa1MouseClicked

    private void jBtnXoa1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoa1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnXoa1MouseEntered

    private void jBtnXoa1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoa1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnXoa1MouseExited

    private void jBtnXoa1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoa1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnXoa1MousePressed

    private void jBtnXoa1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoa1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnXoa1MouseReleased

    private void jBtnSua1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSua1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSua1MouseClicked

    private void jBtnSua1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSua1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSua1MouseEntered

    private void jBtnSua1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSua1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSua1MouseExited

    private void jBtnSua1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSua1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSua1MousePressed

    private void jBtnSua1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSua1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSua1MouseReleased

    private void jBtnLuu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuu1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnLuu1MouseClicked

    private void jBtnLuu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuu1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnLuu1MouseEntered

    private void jBtnLuu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuu1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnLuu1MouseExited

    private void jBtnLuu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuu1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnLuu1MousePressed

    private void jBtnLuu1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuu1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnLuu1MouseReleased

    private void jBtnHuy1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuy1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnHuy1MouseClicked

    private void jBtnHuy1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuy1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnHuy1MouseEntered

    private void jBtnHuy1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuy1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnHuy1MouseExited

    private void jBtnHuy1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuy1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnHuy1MousePressed

    private void jBtnHuy1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuy1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnHuy1MouseReleased

    private void jtxtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTimKiemKeyReleased
        // TODO add your handling code here:
        if (jcbbTimTheo.getSelectedIndex() == 0) {
            HienThiDanhSachKhachHang(CtrlKH.SearchKhachHangByName(jtxtTimKiem.getText()));
        } else if (jcbbTimTheo.getSelectedIndex() == 1) {
            HienThiDanhSachKhachHang(CtrlKH.SearchKhachHangByID(jtxtTimKiem.getText()));
        } else if (jcbbTimTheo.getSelectedIndex() == 2) {
            HienThiDanhSachKhachHang(CtrlKH.SearchKhachHangByDiaChi(jtxtTimKiem.getText()));
        } else if (jcbbTimTheo.getSelectedIndex() == 3) {
            HienThiDanhSachKhachHang(CtrlKH.SearchKhachHangBySDT(jtxtTimKiem.getText()));
        } else {
            HienThiDanhSachKhachHang(CtrlKH.SearchKhachHangBySDT(jtxtTimKiem.getText()));
        }
        Binding();
    }//GEN-LAST:event_jtxtTimKiemKeyReleased

    /**
     * @param args the command line arguments
     */
    public void setColor(JPanel pn) {
        if (pn.isEnabled()) {
            pn.setSize(pn.getWidth() + 1, pn.getHeight() + 1);
            pn.setBackground(new Color(60, 209, 127, 50));
        }
    }

    public void resetColor(JPanel pn) {
        if (pn.isEnabled()) {
            pn.setSize(pn.getWidth() - 1, pn.getHeight() - 1);
            pn.setBackground(new Color(153, 153, 153, 180));
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQuanLiKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQuanLiKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQuanLiKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQuanLiKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQuanLiKhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBtnBack;
    private javax.swing.JPanel jBtnHuy;
    private javax.swing.JPanel jBtnHuy1;
    private javax.swing.JPanel jBtnLamMoi;
    private javax.swing.JPanel jBtnLuu;
    private javax.swing.JPanel jBtnLuu1;
    private javax.swing.JPanel jBtnSua;
    private javax.swing.JPanel jBtnSua1;
    private javax.swing.JPanel jBtnThem;
    private javax.swing.JPanel jBtnThem1;
    private javax.swing.JPanel jBtnTimKiem;
    private javax.swing.JPanel jBtnXoa;
    private javax.swing.JPanel jBtnXoa1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPnDSKH;
    private javax.swing.JPanel jPnThongtinKH;
    private javax.swing.JPanel jPnTracuuKH;
    private javax.swing.JScrollPane jScrDSKH;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbbTimTheo;
    private javax.swing.JLabel jlblHuy;
    private javax.swing.JLabel jlblHuy1;
    private javax.swing.JLabel jlblLuu;
    private javax.swing.JLabel jlblLuu1;
    private javax.swing.JLabel jlblSua;
    private javax.swing.JLabel jlblSua1;
    private javax.swing.JLabel jlblThem;
    private javax.swing.JLabel jlblThem1;
    private javax.swing.JLabel jlblXoa;
    private javax.swing.JLabel jlblXoa1;
    private javax.swing.JTable jtbDSKH;
    private javax.swing.JTextArea jtxtDiaChi;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtMaKH;
    private javax.swing.JTextField jtxtSDT;
    private javax.swing.JTextField jtxtTenKH;
    private javax.swing.JTextField jtxtTienNo;
    private javax.swing.JTextField jtxtTimKiem;
    // End of variables declaration//GEN-END:variables

    public void LoadForm() {
        HienThiDanhSachKhachHang(CtrlKH.LayDanhSachKhachHang());
        Binding();
        EnableComponent(true);
    }

    private void HienThiDanhSachKhachHang(ResultSet rs) {
        listKH.clear();
        DefaultTableModel model;
        model = (DefaultTableModel) jtbDSKH.getModel();
        model.getDataVector().removeAllElements(); //remove data in table
        try {
            while (rs.next()) {
                ObjKhachHang itemKH;
                itemKH = new ObjKhachHang(rs.getString("MaKH"), rs.getString("TenKH"), rs.getString("SDT"), rs.getString("DiaChi"), rs.getString("Email"), rs.getInt("TienNo"));
                listKH.add(itemKH);
                model.addRow(new Object[]{itemKH.getMaKH(), itemKH.getTenKH(), itemKH.getSDT(), String.format("%,d", itemKH.getTienNo())});
            }
        } catch (SQLException ex) {
            System.out.println("Ngoại lệ tại FormQuanLiKhachHang.HienThiDanhSachKhachHang: " + ex.getMessage());
        } finally {
            CtrlKH.CloseConnection();
        }
        jtbDSKH.changeSelection(0, 0, false, false);
    }

    public void Binding() {
        TableModel model = jtbDSKH.getModel();
        try {
            int viewRow = jtbDSKH.getSelectedRow();
            int modelRow = jtbDSKH.convertRowIndexToModel(viewRow);
            if (viewRow > -1) {
                jtxtMaKH.setText(listKH.get(modelRow).getMaKH());
                jtxtTenKH.setText(listKH.get(modelRow).getTenKH());
                jtxtSDT.setText(listKH.get(modelRow).getSDT());
                jtxtDiaChi.setText(listKH.get(modelRow).getDiaChi());
                jtxtEmail.setText(listKH.get(modelRow).getEmail());
                jtxtTienNo.setText(String.format("%,d", listKH.get(modelRow).getTienNo()));
            }
        } catch (Exception ex) {
            System.out.println("Ngoại lệ tại FormQuanLiKhachHang.Binding: " + ex.getMessage());
        }
    }

    private void EnableComponent(boolean Active) {
        jBtnThem.setVisible(Active);
        jBtnXoa.setVisible(Active);
        jBtnSua.setVisible(Active);
        jBtnLuu.setVisible(!Active);
        jBtnHuy.setVisible(!Active);
        jtxtTenKH.setEditable(!Active);
        jtxtSDT.setEnabled(!Active);
        jtxtDiaChi.setEditable(!Active);
        jtxtEmail.setEditable(!Active);
        jtxtTienNo.setEditable(!Active);
    }
}
