/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Connect.Connect;
import Control.CtrlThongKeDoanhThu;

import Edit.Edit;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.naming.spi.DirStateFactory;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ThaiNguyen
 */
public class FormThongKeDoanhThu extends javax.swing.JFrame {

    Edit editFrm = new Edit();
    int xx, yy;
    CtrlThongKeDoanhThu ctrlTKDT = new CtrlThongKeDoanhThu();
    ArrayList<String> ListLoaiSP = new ArrayList<>();
    SimpleDateFormat dt = new SimpleDateFormat("dd/MM/yyyy");

    /**
     * Creates new form FormThongKeTonKho
     */
    public FormThongKeDoanhThu() {
        initComponents();
        setLocationRelativeTo(null);
        JPanel ListPanel[] = new JPanel[]{jPanel2, jPanel3};
        editFrm.MakeTransparentPanel(ListPanel);
        JPanel ListTitle[] = new JPanel[]{jPnDSTonKho, jPnThongketonkho};
        editFrm.MakeTransparentTitle(ListTitle);
        JPanel ListButton[] = new JPanel[]{jBtnBack1, jBtnXemThongKe, jBtnXemBaoCao};
        editFrm.MakeTransparentButton(ListButton);
        editFrm.MakeTransparentTable(jScrDSTK, jTbDSTK);
        LoadForm();
    }

    public void LoadForm() {
        try {
            jDateTuNgay.setDate(new Date());
            jDateDenNgay.setDate(new Date());
            LoadComboboxLSP();
            HienThiDanhSachDoanhThu(ctrlTKDT.LayDanhSachThongKe(ListLoaiSP.get(jcbbLoaiSP.getSelectedIndex()), jtxtTimKiemTenSP.getText(), jDateTuNgay.getDate(), jDateDenNgay.getDate()));
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }

    public void HienThiDanhSachDoanhThu(ResultSet rs) {
        DefaultTableModel model = (DefaultTableModel) jTbDSTK.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        long TongDoanhThu=0;
        try {
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("MaSP"));
                v.add(rs.getString("TenSP"));
                v.add(rs.getString("TenLoaiSP"));
                v.add(rs.getString("DVT"));
                v.add(rs.getString("SoLuong"));
                v.add(String.format("%,d", rs.getInt("DoanhSo")));
                model.addRow(v);
                TongDoanhThu+=rs.getLong("DoanhSo");
            }
            jtxtTongDoanhThu.setText(String.format("%,d", TongDoanhThu));
        } catch (Exception ex) {
            //LoadComboboxKiCongNo();
            System.out.println("Ngoại lệ tại FormThongKeTonKho.HienThiDanhSachTonKho: " + ex.getMessage());
        }
    }

    public void LoadComboboxLSP() {
        ListLoaiSP.clear();
        jcbbLoaiSP.removeAllItems();
        jcbbLoaiSP.addItem("---Chọn loại sản phẩm---");
        ListLoaiSP.add("");
        ResultSet rs = ctrlTKDT.LayDanhSachLoaiSP();
        try {
            while (rs.next()) {
                jcbbLoaiSP.addItem(rs.getString("TenLoaiSP"));
                ListLoaiSP.add(rs.getString("MaLoaiSP"));
            }
        } catch (SQLException ex) {
            System.out.println("Ngoại lệ tại FormThongKeTonKho.LoadComboboxKyTonKho: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnBack1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jBtnXemThongKe = new javax.swing.JPanel();
        jlbLuu = new javax.swing.JLabel();
        jBtnXemBaoCao = new javax.swing.JPanel();
        jlbIn2 = new javax.swing.JLabel();
        jScrDSTK = new javax.swing.JScrollPane();
        jTbDSTK = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPnThongketonkho = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbbLoaiSP = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jDateTuNgay = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jDateDenNgay = new com.toedter.calendar.JDateChooser();
        jtxtTimKiemTenSP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPnDSTonKho = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtTongDoanhThu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thống kê doanh thu");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnBack1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnBack1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnBack1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnBack1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnBack1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnBack1MouseReleased(evt);
            }
        });

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Left_40px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnBack1Layout = new javax.swing.GroupLayout(jBtnBack1);
        jBtnBack1.setLayout(jBtnBack1Layout);
        jBtnBack1Layout.setHorizontalGroup(
            jBtnBack1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnBack1Layout.createSequentialGroup()
                .addComponent(jLabel22)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jBtnBack1Layout.setVerticalGroup(
            jBtnBack1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnBack1Layout.createSequentialGroup()
                .addComponent(jLabel22)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jBtnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jBtnXemThongKe.setBackground(new java.awt.Color(102, 102, 102));
        jBtnXemThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnXemThongKeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnXemThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnXemThongKeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnXemThongKeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnXemThongKeMouseReleased(evt);
            }
        });
        jBtnXemThongKe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbLuu.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jlbLuu.setForeground(new java.awt.Color(255, 255, 255));
        jlbLuu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_view_40px.png"))); // NOI18N
        jlbLuu.setText("  Xem thống kê");
        jBtnXemThongKe.add(jlbLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 40));

        getContentPane().add(jBtnXemThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 98, 165, 60));

        jBtnXemBaoCao.setBackground(new java.awt.Color(102, 102, 102));
        jBtnXemBaoCao.setPreferredSize(new java.awt.Dimension(102, 50));
        jBtnXemBaoCao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnXemBaoCaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnXemBaoCaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnXemBaoCaoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnXemBaoCaoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnXemBaoCaoMouseReleased(evt);
            }
        });
        jBtnXemBaoCao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbIn2.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jlbIn2.setForeground(new java.awt.Color(255, 255, 255));
        jlbIn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbIn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Print_45px.png"))); // NOI18N
        jlbIn2.setText("Xem báo cáo");
        jBtnXemBaoCao.add(jlbIn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 40));

        getContentPane().add(jBtnXemBaoCao, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 98, 165, 60));

        jTbDSTK.setAutoCreateRowSorter(true);
        jTbDSTK.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jTbDSTK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Loại sản phẩm", "Đơn vị tính", "Số lượng bán", "Doanh số"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTbDSTK.setFocusable(false);
        jTbDSTK.setRowHeight(25);
        jTbDSTK.setSelectionForeground(new java.awt.Color(255, 51, 0));
        jTbDSTK.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrDSTK.setViewportView(jTbDSTK);
        if (jTbDSTK.getColumnModel().getColumnCount() > 0) {
            jTbDSTK.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTbDSTK.getColumnModel().getColumn(1).setPreferredWidth(300);
            jTbDSTK.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTbDSTK.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTbDSTK.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTbDSTK.getColumnModel().getColumn(5).setPreferredWidth(100);
        }

        getContentPane().add(jScrDSTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 255, 1270, 380));

        jPanel1.setOpaque(false);
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPnThongketonkho.setBackground(new java.awt.Color(0, 204, 204));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Thống kê tồn kho :");

        javax.swing.GroupLayout jPnThongketonkhoLayout = new javax.swing.GroupLayout(jPnThongketonkho);
        jPnThongketonkho.setLayout(jPnThongketonkhoLayout);
        jPnThongketonkhoLayout.setHorizontalGroup(
            jPnThongketonkhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnThongketonkhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(1152, Short.MAX_VALUE))
        );
        jPnThongketonkhoLayout.setVerticalGroup(
            jPnThongketonkhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPnThongketonkho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        jLabel3.setText("Tra cứu : ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 124, -1, -1));

        jcbbLoaiSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbbLoaiSP.setFocusable(false);
        jcbbLoaiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbbLoaiSPActionPerformed(evt);
            }
        });
        jPanel2.add(jcbbLoaiSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 87, 283, -1));

        jLabel6.setText("Từ ngày :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, 20));

        jDateTuNgay.setDateFormatString("dd/MM/yyyy");
        jPanel2.add(jDateTuNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 120, -1));

        jLabel2.setText("Đến ngày :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, 20));

        jDateDenNgay.setDateFormatString("dd/MM/yyyy");
        jPanel2.add(jDateDenNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 120, -1));

        jtxtTimKiemTenSP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtTimKiemTenSPKeyReleased(evt);
            }
        });
        jPanel2.add(jtxtTimKiemTenSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 120, 283, -1));

        jLabel7.setText("Loại sản phẩm :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 90, -1, -1));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPnDSTonKho.setBackground(new java.awt.Color(0, 204, 204));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Danh sách tồn kho :");

        javax.swing.GroupLayout jPnDSTonKhoLayout = new javax.swing.GroupLayout(jPnDSTonKho);
        jPnDSTonKho.setLayout(jPnDSTonKhoLayout);
        jPnDSTonKhoLayout.setHorizontalGroup(
            jPnDSTonKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnDSTonKhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(1146, Short.MAX_VALUE))
        );
        jPnDSTonKhoLayout.setVerticalGroup(
            jPnDSTonKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel3.add(jPnDSTonKho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 30));

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel4.setText("Tổng doanh thu :");

        jtxtTongDoanhThu.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtTongDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtTongDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 700));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pexels-photo-530024.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBack1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBack1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jBtnBack1MouseClicked

    private void jBtnBack1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBack1MouseEntered
        // TODO add your handling code here:
        setColor(jBtnBack1);
    }//GEN-LAST:event_jBtnBack1MouseEntered

    private void jBtnBack1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBack1MouseExited
        // TODO add your handling code here:
        resetColor(jBtnBack1);
    }//GEN-LAST:event_jBtnBack1MouseExited

    private void jBtnBack1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBack1MousePressed
        // TODO add your handling code here:
        resetColor(jBtnBack1);
    }//GEN-LAST:event_jBtnBack1MousePressed

    private void jBtnBack1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBack1MouseReleased
        // TODO add your handling code here:
        setColor(jBtnBack1);
    }//GEN-LAST:event_jBtnBack1MouseReleased

    private void jBtnXemThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemThongKeMouseClicked
        // TODO add your handling code here:
        HienThiDanhSachDoanhThu(ctrlTKDT.LayDanhSachThongKe(ListLoaiSP.get(jcbbLoaiSP.getSelectedIndex()), jtxtTimKiemTenSP.getText(), jDateTuNgay.getDate(), jDateDenNgay.getDate()));
    }//GEN-LAST:event_jBtnXemThongKeMouseClicked

    private void jBtnXemThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemThongKeMouseEntered
        // TODO add your handling code here:
        setColor(jBtnXemThongKe);
    }//GEN-LAST:event_jBtnXemThongKeMouseEntered

    private void jBtnXemThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemThongKeMouseExited
        // TODO add your handling code here:
        resetColor(jBtnXemThongKe);
    }//GEN-LAST:event_jBtnXemThongKeMouseExited

    private void jBtnXemThongKeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemThongKeMousePressed
        // TODO add your handling code here:
        resetColor(jBtnXemThongKe);
    }//GEN-LAST:event_jBtnXemThongKeMousePressed

    private void jBtnXemThongKeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemThongKeMouseReleased
        // TODO add your handling code here:
        setColor(jBtnXemThongKe);
    }//GEN-LAST:event_jBtnXemThongKeMouseReleased

    private void jBtnXemBaoCaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemBaoCaoMouseClicked
        // TODO add your handling code here:
//        try {
//            Connect con = new Connect();
//            con.Connected();
//            Hashtable hash = new Hashtable();
//            InputStream is = null;
//            is = new FileInputStream("src/Report/ReportTongHopTonKho.jasper");
//            hash.put("MaKTK", objKTK.getMaKTK());
//            JasperPrint print = JasperFillManager.fillReport(is, hash, con.getConDB());
//            JasperViewer.viewReport(print, false);
//        } catch (Exception ex) {
//            System.out.println("Ngoại lệ tại FormThongKeTonKho.jBtnXemBaoCaoMouseClicked:" + ex.getMessage());
//            ex.printStackTrace();
//        }
    }//GEN-LAST:event_jBtnXemBaoCaoMouseClicked

    private void jBtnXemBaoCaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemBaoCaoMouseEntered
        // TODO add your handling code here:
        setColor(jBtnXemBaoCao);
    }//GEN-LAST:event_jBtnXemBaoCaoMouseEntered

    private void jBtnXemBaoCaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemBaoCaoMouseExited
        // TODO add your handling code here:
        resetColor(jBtnXemBaoCao);
    }//GEN-LAST:event_jBtnXemBaoCaoMouseExited

    private void jBtnXemBaoCaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemBaoCaoMousePressed
        // TODO add your handling code here:
        resetColor(jBtnXemBaoCao);
        //        System.out.println("IN");
        //        EnableComponent(true);
    }//GEN-LAST:event_jBtnXemBaoCaoMousePressed

    private void jBtnXemBaoCaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemBaoCaoMouseReleased
        // TODO add your handling code here:
        setColor(jBtnXemBaoCao);
    }//GEN-LAST:event_jBtnXemBaoCaoMouseReleased


    private void jcbbLoaiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbbLoaiSPActionPerformed
        // TODO add your handling code here:
        try {
            if (jcbbLoaiSP.getSelectedIndex() >= 0) {
                HienThiDanhSachDoanhThu(ctrlTKDT.LayDanhSachThongKe(ListLoaiSP.get(jcbbLoaiSP.getSelectedIndex()), jtxtTimKiemTenSP.getText(), jDateTuNgay.getDate(), jDateDenNgay.getDate()));
            }
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_jcbbLoaiSPActionPerformed

    private void jtxtTimKiemTenSPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTimKiemTenSPKeyReleased
        // TODO add your handling code here:
        HienThiDanhSachDoanhThu(ctrlTKDT.LayDanhSachThongKe(ListLoaiSP.get(jcbbLoaiSP.getSelectedIndex()), jtxtTimKiemTenSP.getText(), jDateTuNgay.getDate(), jDateDenNgay.getDate()));
    }//GEN-LAST:event_jtxtTimKiemTenSPKeyReleased

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_jPanel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public void setColor(JPanel pn) {
        if (pn.isEnabled()) {
            pn.setSize(pn.getWidth() + 1, pn.getHeight() + 1);
            pn.setBackground(new Color(60, 209, 127, 50));
        }
    }

    public void resetColor(JPanel pn) {
        if (pn.isEnabled()) {
            pn.setSize(pn.getWidth() - 1, pn.getHeight() - 1);
            pn.setBackground(new Color(153, 153, 153, 180));
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormThongKeDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormThongKeDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormThongKeDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormThongKeDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormThongKeDoanhThu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBtnBack1;
    private javax.swing.JPanel jBtnXemBaoCao;
    private javax.swing.JPanel jBtnXemThongKe;
    private com.toedter.calendar.JDateChooser jDateDenNgay;
    private com.toedter.calendar.JDateChooser jDateTuNgay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPnDSTonKho;
    private javax.swing.JPanel jPnThongketonkho;
    private javax.swing.JScrollPane jScrDSTK;
    private javax.swing.JTable jTbDSTK;
    private javax.swing.JComboBox<String> jcbbLoaiSP;
    private javax.swing.JLabel jlbIn2;
    private javax.swing.JLabel jlbLuu;
    private javax.swing.JTextField jtxtTimKiemTenSP;
    private javax.swing.JTextField jtxtTongDoanhThu;
    // End of variables declaration//GEN-END:variables
}
