/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;


/**
 *
 * @author ThaiNguyen
 */
public class MainForm extends javax.swing.JFrame {

    int xx, yy;
    /**
     * Creates new form MainForm
     */





    MainForm() {
        initComponents();
        setLocationRelativeTo(null);

        jPanel1.setBackground(new Color(0, 0, 0, 80));

        jPnHome.setVisible(false);

        jPnHome.setBackground(new Color(236, 236, 236, 50));

        jBtnTaoTK.setBackground(new Color(236, 236, 236, 50));
        
        jBtnDoiMK.setBackground(new Color(236, 236, 236, 50));
        jBtnThongtin.setBackground(new Color(236, 236, 236, 50));

        jBtnThietlap.setBackground(new Color(236, 236, 236, 50));
        jBtnNguoidung.setBackground(new Color(236, 236, 236, 50));
        jBtnThongke.setBackground(new Color(236, 236, 236, 50));
        jBtnBanhang.setBackground(new Color(236, 236, 236, 50));
        jBtnKhohang.setBackground(new Color(236, 236, 236, 50));
        jBtnKetoan.setBackground(new Color(236, 236, 236, 50));
        jBtn7.setBackground(new Color(236, 236, 236, 50));
        jBtnLapHD.setBackground(new Color(236, 236, 236, 50));
        jBtnLapHDS.setBackground(new Color(236, 236, 236, 50));
        jBtnLapHDL.setBackground(new Color(236, 236, 236, 50));
        jPnHome1.setVisible(false);
    }

    public void setColor(JPanel pn) {
        if (pn.isEnabled()) {
            pn.setSize(pn.getWidth() + 1, pn.getHeight() + 1);
            pn.setBackground(new Color(60, 209, 127, 50));
        }
    }

    public void resetColor(JPanel pn) {
        if (pn.isEnabled()) {
            pn.setSize(pn.getWidth() - 1, pn.getHeight() - 1);
            pn.setBackground(new Color(236, 236, 236, 50));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnThongke = new javax.swing.JPanel();
        jlbThongKe = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBtnLapHD = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jBtnKhohang = new javax.swing.JPanel();
        jlbKhoHang = new javax.swing.JLabel();
        jlbIconKeToan = new javax.swing.JLabel();
        jBtnKetoan = new javax.swing.JPanel();
        jlbKeToan = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jBtnBanhang = new javax.swing.JPanel();
        jlbBanHang = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBtnNguoidung = new javax.swing.JPanel();
        jlbNguoiDung = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jBtnThietlap = new javax.swing.JPanel();
        jlbIconThietLap = new javax.swing.JLabel();
        jlbThietLap = new javax.swing.JLabel();
        jPnHome1 = new javax.swing.JPanel();
        jBtnLapHDL = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jBtnLapHDS = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jBtnClose = new javax.swing.JLabel();
        jBtn7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPnHome = new javax.swing.JPanel();
        jBtnTaoTK = new javax.swing.JPanel();
        jlbTaoTK = new javax.swing.JLabel();
        jBtnDoiMK = new javax.swing.JPanel();
        jlbDoiMK = new javax.swing.JLabel();
        jBtnThongtin = new javax.swing.JPanel();
        jlbThongTin = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Màn hình chính");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnThongke.setBackground(new java.awt.Color(153, 153, 153));
        jBtnThongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnThongkeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnThongkeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnThongkeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnThongkeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnThongkeMouseReleased(evt);
            }
        });
        jBtnThongke.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbThongKe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbThongKe.setForeground(new java.awt.Color(255, 255, 255));
        jlbThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbThongKe.setText("Quản lý sản phẩm");
        jBtnThongke.add(jlbThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Product_70px.png"))); // NOI18N
        jBtnThongke.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 80, 60));

        getContentPane().add(jBtnThongke, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 180, 120));

        jBtnLapHD.setBackground(new java.awt.Color(153, 153, 153));
        jBtnLapHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLapHDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnLapHDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnLapHDMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnLapHDMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnLapHDMouseReleased(evt);
            }
        });
        jBtnLapHD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Invoice_64px_1.png"))); // NOI18N
        jBtnLapHD.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 10, -1, 80));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Lập hóa đơn");
        jBtnLapHD.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 80, -1));

        getContentPane().add(jBtnLapHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 180, 120));

        jBtnKhohang.setBackground(new java.awt.Color(153, 153, 153));
        jBtnKhohang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnKhohangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnKhohangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnKhohangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnKhohangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnKhohangMouseReleased(evt);
            }
        });
        jBtnKhohang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbKhoHang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbKhoHang.setForeground(new java.awt.Color(255, 255, 255));
        jlbKhoHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbKhoHang.setText("Quản lý thu tiền");
        jBtnKhohang.add(jlbKhoHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, -1));

        jlbIconKeToan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbIconKeToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Coins_64px.png"))); // NOI18N
        jBtnKhohang.add(jlbIconKeToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 80, 60));

        getContentPane().add(jBtnKhohang, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 180, 120));

        jBtnKetoan.setBackground(new java.awt.Color(153, 153, 153));
        jBtnKetoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnKetoanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnKetoanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnKetoanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnKetoanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnKetoanMouseReleased(evt);
            }
        });
        jBtnKetoan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbKeToan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbKeToan.setForeground(new java.awt.Color(255, 255, 255));
        jlbKeToan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbKeToan.setText("Danh sách khách hàng");
        jBtnKetoan.add(jlbKeToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 160, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Business_Building_68px.png"))); // NOI18N
        jBtnKetoan.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        getContentPane().add(jBtnKetoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 180, 120));

        jBtnBanhang.setBackground(new java.awt.Color(153, 153, 153));
        jBtnBanhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnBanhangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnBanhangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnBanhangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnBanhangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnBanhangMouseReleased(evt);
            }
        });
        jBtnBanhang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbBanHang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbBanHang.setForeground(new java.awt.Color(255, 255, 255));
        jlbBanHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbBanHang.setText("Danh sách hoá đơn");
        jBtnBanhang.add(jlbBanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Content_64px.png"))); // NOI18N
        jBtnBanhang.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        getContentPane().add(jBtnBanhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 180, 120));

        jBtnNguoidung.setBackground(new java.awt.Color(153, 153, 153));
        jBtnNguoidung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnNguoidungMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnNguoidungMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnNguoidungMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnNguoidungMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnNguoidungMouseReleased(evt);
            }
        });
        jBtnNguoidung.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbNguoiDung.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbNguoiDung.setForeground(new java.awt.Color(255, 255, 255));
        jlbNguoiDung.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNguoiDung.setText("Quản lý loại sản phẩm");
        jBtnNguoidung.add(jlbNguoiDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 160, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Trolley_70px.png"))); // NOI18N
        jBtnNguoidung.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 60, 60));

        getContentPane().add(jBtnNguoidung, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 180, 120));

        jBtnThietlap.setBackground(new java.awt.Color(153, 153, 153));
        jBtnThietlap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnThietlapMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnThietlapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnThietlapMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnThietlapMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnThietlapMouseReleased(evt);
            }
        });
        jBtnThietlap.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbIconThietLap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbIconThietLap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Settings_64px.png"))); // NOI18N
        jBtnThietlap.add(jlbIconThietLap, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 20, 70, 60));

        jlbThietLap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbThietLap.setForeground(new java.awt.Color(255, 255, 255));
        jlbThietLap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbThietLap.setText("Thiết lập");
        jBtnThietlap.add(jlbThietLap, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, -1));

        getContentPane().add(jBtnThietlap, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 180, 120));

        jPnHome1.setBackground(new java.awt.Color(204, 204, 204));
        jPnHome1.setOpaque(false);
        jPnHome1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnLapHDL.setBackground(new java.awt.Color(153, 153, 153));
        jBtnLapHDL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLapHDLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnLapHDLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnLapHDLMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnLapHDLMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnLapHDLMouseReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Lập hóa đơn lẻ");

        javax.swing.GroupLayout jBtnLapHDLLayout = new javax.swing.GroupLayout(jBtnLapHDL);
        jBtnLapHDL.setLayout(jBtnLapHDLLayout);
        jBtnLapHDLLayout.setHorizontalGroup(
            jBtnLapHDLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnLapHDLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jBtnLapHDLLayout.setVerticalGroup(
            jBtnLapHDLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBtnLapHDLLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(11, 11, 11))
        );

        jPnHome1.add(jBtnLapHDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 38));

        jBtnLapHDS.setBackground(new java.awt.Color(102, 102, 102));
        jBtnLapHDS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLapHDSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnLapHDSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnLapHDSMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnLapHDSMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnLapHDSMouseReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Lập hóa đơn sỉ");

        javax.swing.GroupLayout jBtnLapHDSLayout = new javax.swing.GroupLayout(jBtnLapHDS);
        jBtnLapHDS.setLayout(jBtnLapHDSLayout);
        jBtnLapHDSLayout.setHorizontalGroup(
            jBtnLapHDSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnLapHDSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jBtnLapHDSLayout.setVerticalGroup(
            jBtnLapHDSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnLapHDSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPnHome1.add(jBtnLapHDS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 38, 190, 38));

        getContentPane().add(jPnHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 349, -1, -1));

        jBtnClose.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jBtnClose.setForeground(new java.awt.Color(255, 255, 255));
        jBtnClose.setText("X");
        jBtnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCloseMouseClicked(evt);
            }
        });
        getContentPane().add(jBtnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 20, 30));

        jBtn7.setBackground(new java.awt.Color(204, 204, 204));
        jBtn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtn7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtn7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtn7MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtn7MouseReleased(evt);
            }
        });
        jBtn7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Menu_40px.png"))); // NOI18N
        jBtn7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 60, 40));

        getContentPane().add(jBtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 60));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/navigation.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 80, 80));

        jLabel14.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(" Tân An Store");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, -1));

        jLabel16.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Support Management");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, -1));

        jPnHome.setBackground(new java.awt.Color(204, 204, 204));
        jPnHome.setOpaque(false);
        jPnHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnTaoTK.setBackground(new java.awt.Color(153, 153, 153));
        jBtnTaoTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnTaoTKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnTaoTKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnTaoTKMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnTaoTKMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnTaoTKMouseReleased(evt);
            }
        });

        jlbTaoTK.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbTaoTK.setForeground(new java.awt.Color(255, 255, 255));
        jlbTaoTK.setText("Đổi mật khẩu");

        javax.swing.GroupLayout jBtnTaoTKLayout = new javax.swing.GroupLayout(jBtnTaoTK);
        jBtnTaoTK.setLayout(jBtnTaoTKLayout);
        jBtnTaoTKLayout.setHorizontalGroup(
            jBtnTaoTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnTaoTKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTaoTK)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jBtnTaoTKLayout.setVerticalGroup(
            jBtnTaoTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnTaoTKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTaoTK, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPnHome.add(jBtnTaoTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        jBtnDoiMK.setBackground(new java.awt.Color(102, 102, 102));
        jBtnDoiMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnDoiMKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnDoiMKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnDoiMKMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnDoiMKMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnDoiMKMouseReleased(evt);
            }
        });

        jlbDoiMK.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbDoiMK.setForeground(new java.awt.Color(255, 255, 255));
        jlbDoiMK.setText("Thông tin");

        javax.swing.GroupLayout jBtnDoiMKLayout = new javax.swing.GroupLayout(jBtnDoiMK);
        jBtnDoiMK.setLayout(jBtnDoiMKLayout);
        jBtnDoiMKLayout.setHorizontalGroup(
            jBtnDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnDoiMKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbDoiMK)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jBtnDoiMKLayout.setVerticalGroup(
            jBtnDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBtnDoiMKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbDoiMK, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPnHome.add(jBtnDoiMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 180, 38));

        jBtnThongtin.setBackground(new java.awt.Color(51, 51, 51));
        jBtnThongtin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnThongtinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnThongtinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnThongtinMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnThongtinMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnThongtinMouseReleased(evt);
            }
        });

        jlbThongTin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbThongTin.setForeground(new java.awt.Color(255, 255, 255));
        jlbThongTin.setText("Đăng xuất");

        javax.swing.GroupLayout jBtnThongtinLayout = new javax.swing.GroupLayout(jBtnThongtin);
        jBtnThongtin.setLayout(jBtnThongtinLayout);
        jBtnThongtinLayout.setHorizontalGroup(
            jBtnThongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnThongtinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbThongTin)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jBtnThongtinLayout.setVerticalGroup(
            jBtnThongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnThongtinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPnHome.add(jBtnThongtin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 78, 180, 38));

        getContentPane().add(jPnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 79, 180, 120));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Design, Create By Thái Nguyễn");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 600, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 630));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/FormMain.PNG"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

  

    private void jBtnBanhangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBanhangMouseEntered
        // TODO add your handling code here:
        setColor(jBtnBanhang);
    }//GEN-LAST:event_jBtnBanhangMouseEntered

    private void jBtnBanhangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBanhangMouseExited
        // TODO add your handling code here:
        resetColor(jBtnBanhang);
    }//GEN-LAST:event_jBtnBanhangMouseExited

    private void jBtnKhohangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnKhohangMouseEntered
        // TODO add your handling code here:
        setColor(jBtnKhohang);
    }//GEN-LAST:event_jBtnKhohangMouseEntered

    private void jBtnKhohangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnKhohangMouseExited
        // TODO add your handling code here:
        resetColor(jBtnKhohang);

    }//GEN-LAST:event_jBtnKhohangMouseExited

    private void jBtnKetoanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnKetoanMouseEntered
        // TODO add your handling code here:
        setColor(jBtnKetoan);
    }//GEN-LAST:event_jBtnKetoanMouseEntered

    private void jBtnKetoanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnKetoanMouseExited
        // TODO add your handling code here:
        resetColor(jBtnKetoan);
    }//GEN-LAST:event_jBtnKetoanMouseExited

    private void jBtnThongkeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongkeMouseEntered
        // TODO add your handling code here:
        setColor(jBtnThongke);
    }//GEN-LAST:event_jBtnThongkeMouseEntered

    private void jBtnThongkeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongkeMouseExited
        // TODO add your handling code here:
        resetColor(jBtnThongke);
    }//GEN-LAST:event_jBtnThongkeMouseExited

    private void jBtnNguoidungMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnNguoidungMouseEntered
        // TODO add your handling code here:
        setColor(jBtnNguoidung);
    }//GEN-LAST:event_jBtnNguoidungMouseEntered

    private void jBtnNguoidungMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnNguoidungMouseExited
        // TODO add your handling code here:
        resetColor(jBtnNguoidung);
    }//GEN-LAST:event_jBtnNguoidungMouseExited

    private void jBtnThietlapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThietlapMouseEntered
        // TODO add your handling code here:
        setColor(jBtnThietlap);
    }//GEN-LAST:event_jBtnThietlapMouseEntered

    private void jBtnThietlapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThietlapMouseExited
        // TODO add your handling code here:
        resetColor(jBtnThietlap);
    }//GEN-LAST:event_jBtnThietlapMouseExited

    private void jBtnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCloseMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jBtnCloseMouseClicked

    private void jBtn7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn7MouseEntered
        // TODO add your handling code here:
        setColor(jBtn7);
    }//GEN-LAST:event_jBtn7MouseEntered

    private void jBtn7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn7MouseExited
        // TODO add your handling code here:
        resetColor(jBtn7);

    }//GEN-LAST:event_jBtn7MouseExited

    private void jBtnBanhangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBanhangMousePressed
        // TODO add your handling code here:
        resetColor(jBtnBanhang);
    }//GEN-LAST:event_jBtnBanhangMousePressed

    private void jBtnBanhangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBanhangMouseReleased
        // TODO add your handling code here:
        if (jBtnBanhang.getBackground().equals(new Color(236, 236, 236, 50))) {
            setColor(jBtnBanhang);
        }
    }//GEN-LAST:event_jBtnBanhangMouseReleased

    private void jBtnKhohangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnKhohangMousePressed
        // TODO add your handling code here:
        resetColor(jBtnKhohang);
    }//GEN-LAST:event_jBtnKhohangMousePressed

    private void jBtnKhohangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnKhohangMouseReleased
        // TODO add your handling code here:
        setColor(jBtnKhohang);
    }//GEN-LAST:event_jBtnKhohangMouseReleased

    private void jBtnKetoanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnKetoanMousePressed
        // TODO add your handling code here:
        resetColor(jBtnKetoan);
    }//GEN-LAST:event_jBtnKetoanMousePressed

    private void jBtnKetoanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnKetoanMouseReleased
        // TODO add your handling code here:
        setColor(jBtnKetoan);
    }//GEN-LAST:event_jBtnKetoanMouseReleased

    private void jBtnThongkeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongkeMousePressed
        // TODO add your handling code here:
        resetColor(jBtnThongke);
    }//GEN-LAST:event_jBtnThongkeMousePressed

    private void jBtnThongkeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongkeMouseReleased
        // TODO add your handling code here:
        setColor(jBtnThongke);
    }//GEN-LAST:event_jBtnThongkeMouseReleased

    private void jBtnNguoidungMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnNguoidungMousePressed
        // TODO add your handling code here:
        resetColor(jBtnNguoidung);
    }//GEN-LAST:event_jBtnNguoidungMousePressed

    private void jBtnNguoidungMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnNguoidungMouseReleased
        // TODO add your handling code here:
        setColor(jBtnNguoidung);
    }//GEN-LAST:event_jBtnNguoidungMouseReleased

    private void jBtnThietlapMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThietlapMousePressed
        // TODO add your handling code here:
        resetColor(jBtnThietlap);
    }//GEN-LAST:event_jBtnThietlapMousePressed

    private void jBtnThietlapMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThietlapMouseReleased
        // TODO add your handling code here:
        setColor(jBtnThietlap);
    }//GEN-LAST:event_jBtnThietlapMouseReleased

    private void jBtn7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn7MousePressed
        // TODO add your handling code here:
        resetColor(jBtn7);
    }//GEN-LAST:event_jBtn7MousePressed

    private void jBtn7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn7MouseReleased
        // TODO add your handling code here:
        setColor(jBtn7);
    }//GEN-LAST:event_jBtn7MouseReleased

    private void jBtnBanhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBanhangMouseClicked
        // TODO add your handling code here:
        new FormDanhSachHoaDon().setVisible(true);
    }//GEN-LAST:event_jBtnBanhangMouseClicked

    private void jBtnKhohangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnKhohangMouseClicked
        // TODO add your handling code here:
        new FormQuanLiPhieuThu().setVisible(true);
    }//GEN-LAST:event_jBtnKhohangMouseClicked

    private void jBtnKetoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnKetoanMouseClicked
        // TODO add your handling code here:
        new FormQuanLiKhachHang().setVisible(true);
    }//GEN-LAST:event_jBtnKetoanMouseClicked

    private void jBtnThongkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongkeMouseClicked
        // TODO add your handling code here:
        new FormQuanLiSanPham().setVisible(true);
    }//GEN-LAST:event_jBtnThongkeMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jBtnDoiMKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDoiMKMouseEntered
        // TODO add your handling code here:
        setColor(jBtnDoiMK);
    }//GEN-LAST:event_jBtnDoiMKMouseEntered

    private void jBtnDoiMKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDoiMKMouseExited
        // TODO add your handling code here:
        resetColor(jBtnDoiMK);
    }//GEN-LAST:event_jBtnDoiMKMouseExited

    private void jBtnThongtinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongtinMouseEntered
        // TODO add your handling code here:
        setColor(jBtnThongtin);
    }//GEN-LAST:event_jBtnThongtinMouseEntered

    private void jBtnThongtinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongtinMouseExited
        // TODO add your handling code here:
        resetColor(jBtnThongtin);
    }//GEN-LAST:event_jBtnThongtinMouseExited

    private void jBtn7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn7MouseClicked
        // TODO add your handling code here:
        if (jPnHome.isVisible()) {
            jPnHome.setVisible(false);
        } else {
            jPnHome.setVisible(true);
        }
    }//GEN-LAST:event_jBtn7MouseClicked

    private void jBtnDoiMKMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDoiMKMousePressed
        // TODO add your handling code here:
        resetColor(jBtnDoiMK);
    }//GEN-LAST:event_jBtnDoiMKMousePressed

    private void jBtnDoiMKMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDoiMKMouseReleased
        // TODO add your handling code here:
        setColor(jBtnDoiMK);
    }//GEN-LAST:event_jBtnDoiMKMouseReleased

    private void jBtnThongtinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongtinMousePressed
        // TODO add your handling code here:
        resetColor(jBtnThongtin);
    }//GEN-LAST:event_jBtnThongtinMousePressed

    private void jBtnThongtinMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongtinMouseReleased
        // TODO add your handling code here:
        setColor(jBtnThongtin);
    }//GEN-LAST:event_jBtnThongtinMouseReleased

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        jPnHome.setVisible(false);
        jPnHome1.setVisible(false);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jBtnNguoidungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnNguoidungMouseClicked
        // TODO add your handling code here:
        new FormQuanLiLoaiSanPham().setVisible(true);
    }//GEN-LAST:event_jBtnNguoidungMouseClicked


    private void jBtnThietlapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThietlapMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jBtnThietlapMouseClicked

    private void jBtnDoiMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDoiMKMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnDoiMKMouseClicked


    private void jBtnThongtinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongtinMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnThongtinMouseClicked

    private void jBtnLapHDLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLapHDLMouseClicked
        // TODO add your handling code here:
        new FormLapHoaDonLe().setVisible(true);
    }//GEN-LAST:event_jBtnLapHDLMouseClicked

    private void jBtnLapHDLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLapHDLMouseEntered
        // TODO add your handling code here:
        setColor(jBtnLapHDL);
    }//GEN-LAST:event_jBtnLapHDLMouseEntered

    private void jBtnLapHDLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLapHDLMouseExited
        // TODO add your handling code here:
        resetColor(jBtnLapHDL);
    }//GEN-LAST:event_jBtnLapHDLMouseExited

    private void jBtnLapHDLMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLapHDLMousePressed
        // TODO add your handling code here:
        resetColor(jBtnLapHDL);
    }//GEN-LAST:event_jBtnLapHDLMousePressed

    private void jBtnLapHDLMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLapHDLMouseReleased
        // TODO add your handling code here:
        setColor(jBtnLapHDL);
    }//GEN-LAST:event_jBtnLapHDLMouseReleased

    private void jBtnLapHDSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLapHDSMouseClicked
        // TODO add your handling code here:
        new FormLapHoaDonSi().setVisible(true);
    }//GEN-LAST:event_jBtnLapHDSMouseClicked

    private void jBtnLapHDSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLapHDSMouseEntered
        // TODO add your handling code here:
        setColor(jBtnLapHDS);
    }//GEN-LAST:event_jBtnLapHDSMouseEntered

    private void jBtnLapHDSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLapHDSMouseExited
        // TODO add your handling code here:
        resetColor(jBtnLapHDS);
    }//GEN-LAST:event_jBtnLapHDSMouseExited

    private void jBtnLapHDSMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLapHDSMousePressed
        // TODO add your handling code here:
        resetColor(jBtnLapHDS);
    }//GEN-LAST:event_jBtnLapHDSMousePressed

    private void jBtnLapHDSMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLapHDSMouseReleased
        // TODO add your handling code here:
        setColor(jBtnLapHDS);
    }//GEN-LAST:event_jBtnLapHDSMouseReleased

    private void jBtnLapHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLapHDMouseClicked
        // TODO add your handling code here:
        if(jPnHome1.isVisible())
        jPnHome1.setVisible(false);
        else jPnHome1.setVisible(true);
    }//GEN-LAST:event_jBtnLapHDMouseClicked

    private void jBtnLapHDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLapHDMouseEntered
        // TODO add your handling code here:
        setColor(jBtnLapHD);
    }//GEN-LAST:event_jBtnLapHDMouseEntered

    private void jBtnLapHDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLapHDMouseExited
        // TODO add your handling code here:
        resetColor(jBtnLapHD);
    }//GEN-LAST:event_jBtnLapHDMouseExited

    private void jBtnLapHDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLapHDMousePressed
        // TODO add your handling code here:
        resetColor(jBtnLapHD);
    }//GEN-LAST:event_jBtnLapHDMousePressed

    private void jBtnLapHDMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLapHDMouseReleased
        // TODO add your handling code here:
        if(jBtnLapHD.getBackground().equals(new Color(236,236,236,50))){
            setColor(jBtnLapHD);
        }
    }//GEN-LAST:event_jBtnLapHDMouseReleased

    private void jBtnTaoTKMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTaoTKMouseReleased
        // TODO add your handling code here:
        setColor(jBtnTaoTK);
    }//GEN-LAST:event_jBtnTaoTKMouseReleased

    private void jBtnTaoTKMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTaoTKMousePressed
        // TODO add your handling code here:
        resetColor(jBtnTaoTK);
    }//GEN-LAST:event_jBtnTaoTKMousePressed

    private void jBtnTaoTKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTaoTKMouseExited
        // TODO add your handling code here:
        resetColor(jBtnTaoTK);
    }//GEN-LAST:event_jBtnTaoTKMouseExited

    private void jBtnTaoTKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTaoTKMouseEntered
        // TODO add your handling code here:
        setColor(jBtnTaoTK);
    }//GEN-LAST:event_jBtnTaoTKMouseEntered

    private void jBtnTaoTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTaoTKMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnTaoTKMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBtn7;
    private javax.swing.JPanel jBtnBanhang;
    private javax.swing.JLabel jBtnClose;
    private javax.swing.JPanel jBtnDoiMK;
    private javax.swing.JPanel jBtnKetoan;
    private javax.swing.JPanel jBtnKhohang;
    private javax.swing.JPanel jBtnLapHD;
    private javax.swing.JPanel jBtnLapHDL;
    private javax.swing.JPanel jBtnLapHDS;
    private javax.swing.JPanel jBtnNguoidung;
    private javax.swing.JPanel jBtnTaoTK;
    private javax.swing.JPanel jBtnThietlap;
    private javax.swing.JPanel jBtnThongke;
    private javax.swing.JPanel jBtnThongtin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPnHome;
    private javax.swing.JPanel jPnHome1;
    private javax.swing.JLabel jlbBanHang;
    private javax.swing.JLabel jlbDoiMK;
    private javax.swing.JLabel jlbIconKeToan;
    private javax.swing.JLabel jlbIconThietLap;
    private javax.swing.JLabel jlbKeToan;
    private javax.swing.JLabel jlbKhoHang;
    private javax.swing.JLabel jlbNguoiDung;
    private javax.swing.JLabel jlbTaoTK;
    private javax.swing.JLabel jlbThietLap;
    private javax.swing.JLabel jlbThongKe;
    private javax.swing.JLabel jlbThongTin;
    // End of variables declaration//GEN-END:variables
}
